# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Namespace
metadata:
  name: ate-agent-example
---
apiVersion: ate.gke.io/v1alpha1
kind: WorkerPool
metadata:
  name: ate-agent-workerpool
  namespace: ate-agent-example
spec:
  replicas: 10
  container:
    image: gcr.io/ax-container-images/ate_agent:latest
    ports:
    - containerPort: 50051
---
apiVersion: ate.gke.io/v1alpha1
kind: ActorTemplate
metadata:
  name: ate-agent-template
  namespace: ate-agent-example
spec:
  workerPoolRef:
    name: ate-agent-workerpool
  snapshotsConfig:
    location:
      bucket: ate-agent-snapshots
      folder: ate-agent-example
