// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/testagent/proto/testagent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KubernetesDeployAgentConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []string               `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesDeployAgentConfig) Reset() {
	*x = KubernetesDeployAgentConfig{}
	mi := &file_internal_testagent_proto_testagent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesDeployAgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesDeployAgentConfig) ProtoMessage() {}

func (x *KubernetesDeployAgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testagent_proto_testagent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesDeployAgentConfig.ProtoReflect.Descriptor instead.
func (*KubernetesDeployAgentConfig) Descriptor() ([]byte, []int) {
	return file_internal_testagent_proto_testagent_proto_rawDescGZIP(), []int{0}
}

func (x *KubernetesDeployAgentConfig) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

var File_internal_testagent_proto_testagent_proto protoreflect.FileDescriptor

const file_internal_testagent_proto_testagent_proto_rawDesc = "" +
	"\n" +
	"(internal/testagent/proto/testagent.proto\x12\x05proto\"7\n" +
	"\x1bKubernetesDeployAgentConfig\x12\x18\n" +
	"\aregions\x18\x01 \x03(\tR\aregionsB/Z-github.com/google/ax/internal/testagent/protob\x06proto3"

var (
	file_internal_testagent_proto_testagent_proto_rawDescOnce sync.Once
	file_internal_testagent_proto_testagent_proto_rawDescData []byte
)

func file_internal_testagent_proto_testagent_proto_rawDescGZIP() []byte {
	file_internal_testagent_proto_testagent_proto_rawDescOnce.Do(func() {
		file_internal_testagent_proto_testagent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testagent_proto_testagent_proto_rawDesc), len(file_internal_testagent_proto_testagent_proto_rawDesc)))
	})
	return file_internal_testagent_proto_testagent_proto_rawDescData
}

var file_internal_testagent_proto_testagent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_testagent_proto_testagent_proto_goTypes = []any{
	(*KubernetesDeployAgentConfig)(nil), // 0: proto.KubernetesDeployAgentConfig
}
var file_internal_testagent_proto_testagent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_testagent_proto_testagent_proto_init() }
func file_internal_testagent_proto_testagent_proto_init() {
	if File_internal_testagent_proto_testagent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testagent_proto_testagent_proto_rawDesc), len(file_internal_testagent_proto_testagent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_testagent_proto_testagent_proto_goTypes,
		DependencyIndexes: file_internal_testagent_proto_testagent_proto_depIdxs,
		MessageInfos:      file_internal_testagent_proto_testagent_proto_msgTypes,
	}.Build()
	File_internal_testagent_proto_testagent_proto = out.File
	file_internal_testagent_proto_testagent_proto_goTypes = nil
	file_internal_testagent_proto_testagent_proto_depIdxs = nil
}
