// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/ax.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State represents the state of an execution
type State int32

const (
	State_STATE_UNSPECIFIED State = 0 // Unspecified state
	State_STATE_PENDING     State = 1
	State_STATE_FAILED      State = 2
	State_STATE_COMPLETED   State = 3
	State_STATE_CANCELED    State = 4
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_PENDING",
		2: "STATE_FAILED",
		3: "STATE_COMPLETED",
		4: "STATE_CANCELED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_PENDING":     1,
		"STATE_FAILED":      2,
		"STATE_COMPLETED":   3,
		"STATE_CANCELED":    4,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ax_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_ax_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{0}
}

// CancelReason explains why an in-flight execution is canceled.
type CancelReason int32

const (
	CancelReason_CANCEL_REASON_UNSPECIFIED    CancelReason = 0
	CancelReason_CANCEL_REASON_USER_REQUESTED CancelReason = 1
	CancelReason_CANCEL_REASON_TIMEOUT        CancelReason = 2
	CancelReason_CANCEL_REASON_INTERNAL_ERROR CancelReason = 3
)

// Enum value maps for CancelReason.
var (
	CancelReason_name = map[int32]string{
		0: "CANCEL_REASON_UNSPECIFIED",
		1: "CANCEL_REASON_USER_REQUESTED",
		2: "CANCEL_REASON_TIMEOUT",
		3: "CANCEL_REASON_INTERNAL_ERROR",
	}
	CancelReason_value = map[string]int32{
		"CANCEL_REASON_UNSPECIFIED":    0,
		"CANCEL_REASON_USER_REQUESTED": 1,
		"CANCEL_REASON_TIMEOUT":        2,
		"CANCEL_REASON_INTERNAL_ERROR": 3,
	}
)

func (x CancelReason) Enum() *CancelReason {
	p := new(CancelReason)
	*p = x
	return p
}

func (x CancelReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CancelReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ax_proto_enumTypes[1].Descriptor()
}

func (CancelReason) Type() protoreflect.EnumType {
	return &file_proto_ax_proto_enumTypes[1]
}

func (x CancelReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CancelReason.Descriptor instead.
func (CancelReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{1}
}

// Message is a message in the history.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`       // user, assistant, or model
	Content       *Content               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // content of the message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_ax_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

// A conversation is the historical session that consist of
// a number of execution. A conversation cannot be continued
// before the last execution is completed or failed.
type ConversationEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Seq            int32                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	ExecId         string                 `protobuf:"bytes,3,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	HarnessId      string                 `protobuf:"bytes,4,opt,name=harness_id,json=harnessId,proto3" json:"harness_id,omitempty"`
	HarnessConfig  *structpb.Struct       `protobuf:"bytes,5,opt,name=harness_config,json=harnessConfig,proto3" json:"harness_config,omitempty"`
	Messages       []*Message             `protobuf:"bytes,6,rep,name=messages,proto3" json:"messages,omitempty"`
	State          State                  `protobuf:"varint,7,opt,name=state,proto3,enum=ax.State" json:"state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationEvent) Reset() {
	*x = ConversationEvent{}
	mi := &file_proto_ax_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationEvent) ProtoMessage() {}

func (x *ConversationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationEvent.ProtoReflect.Descriptor instead.
func (*ConversationEvent) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{1}
}

func (x *ConversationEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationEvent) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ConversationEvent) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ConversationEvent) GetHarnessId() string {
	if x != nil {
		return x.HarnessId
	}
	return ""
}

func (x *ConversationEvent) GetHarnessConfig() *structpb.Struct {
	if x != nil {
		return x.HarnessConfig
	}
	return nil
}

func (x *ConversationEvent) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ConversationEvent) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

type HarnessStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-execution harness configuration.
	HarnessConfig []byte     `protobuf:"bytes,1,opt,name=harness_config,json=harnessConfig,proto3" json:"harness_config,omitempty"`
	Messages      []*Message `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessStart) Reset() {
	*x = HarnessStart{}
	mi := &file_proto_ax_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessStart) ProtoMessage() {}

func (x *HarnessStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessStart.ProtoReflect.Descriptor instead.
func (*HarnessStart) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{2}
}

func (x *HarnessStart) GetHarnessConfig() []byte {
	if x != nil {
		return x.HarnessConfig
	}
	return nil
}

func (x *HarnessStart) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// HarnessCancel aborts the in-flight harness execution.
type HarnessCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        CancelReason           `protobuf:"varint,1,opt,name=reason,proto3,enum=ax.CancelReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessCancel) Reset() {
	*x = HarnessCancel{}
	mi := &file_proto_ax_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessCancel) ProtoMessage() {}

func (x *HarnessCancel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessCancel.ProtoReflect.Descriptor instead.
func (*HarnessCancel) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{3}
}

func (x *HarnessCancel) GetReason() CancelReason {
	if x != nil {
		return x.Reason
	}
	return CancelReason_CANCEL_REASON_UNSPECIFIED
}

type HarnessRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	HarnessId      string                 `protobuf:"bytes,2,opt,name=harness_id,json=harnessId,proto3" json:"harness_id,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*HarnessRequest_Start
	//	*HarnessRequest_Cancel
	Type          isHarnessRequest_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessRequest) Reset() {
	*x = HarnessRequest{}
	mi := &file_proto_ax_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessRequest) ProtoMessage() {}

func (x *HarnessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessRequest.ProtoReflect.Descriptor instead.
func (*HarnessRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{4}
}

func (x *HarnessRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *HarnessRequest) GetHarnessId() string {
	if x != nil {
		return x.HarnessId
	}
	return ""
}

func (x *HarnessRequest) GetType() isHarnessRequest_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *HarnessRequest) GetStart() *HarnessStart {
	if x != nil {
		if x, ok := x.Type.(*HarnessRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *HarnessRequest) GetCancel() *HarnessCancel {
	if x != nil {
		if x, ok := x.Type.(*HarnessRequest_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isHarnessRequest_Type interface {
	isHarnessRequest_Type()
}

type HarnessRequest_Start struct {
	Start *HarnessStart `protobuf:"bytes,3,opt,name=start,proto3,oneof"`
}

type HarnessRequest_Cancel struct {
	Cancel *HarnessCancel `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

func (*HarnessRequest_Start) isHarnessRequest_Type() {}

func (*HarnessRequest_Cancel) isHarnessRequest_Type() {}

type HarnessOutputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessOutputs) Reset() {
	*x = HarnessOutputs{}
	mi := &file_proto_ax_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessOutputs) ProtoMessage() {}

func (x *HarnessOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessOutputs.ProtoReflect.Descriptor instead.
func (*HarnessOutputs) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{5}
}

func (x *HarnessOutputs) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A status code, corresponds to google.golang.org/grpc/codes.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// A description of the error.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_ax_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type HarnessEnd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Terminal state for the harness execution.
	State State `protobuf:"varint,1,opt,name=state,proto3,enum=ax.State" json:"state,omitempty"`
	// Optional error details.
	Error         *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessEnd) Reset() {
	*x = HarnessEnd{}
	mi := &file_proto_ax_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessEnd) ProtoMessage() {}

func (x *HarnessEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessEnd.ProtoReflect.Descriptor instead.
func (*HarnessEnd) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{7}
}

func (x *HarnessEnd) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *HarnessEnd) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type HarnessResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*HarnessResponse_Outputs
	//	*HarnessResponse_End
	Type          isHarnessResponse_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessResponse) Reset() {
	*x = HarnessResponse{}
	mi := &file_proto_ax_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessResponse) ProtoMessage() {}

func (x *HarnessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessResponse.ProtoReflect.Descriptor instead.
func (*HarnessResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{8}
}

func (x *HarnessResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *HarnessResponse) GetType() isHarnessResponse_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *HarnessResponse) GetOutputs() *HarnessOutputs {
	if x != nil {
		if x, ok := x.Type.(*HarnessResponse_Outputs); ok {
			return x.Outputs
		}
	}
	return nil
}

func (x *HarnessResponse) GetEnd() *HarnessEnd {
	if x != nil {
		if x, ok := x.Type.(*HarnessResponse_End); ok {
			return x.End
		}
	}
	return nil
}

type isHarnessResponse_Type interface {
	isHarnessResponse_Type()
}

type HarnessResponse_Outputs struct {
	Outputs *HarnessOutputs `protobuf:"bytes,2,opt,name=outputs,proto3,oneof"`
}

type HarnessResponse_End struct {
	End *HarnessEnd `protobuf:"bytes,3,opt,name=end,proto3,oneof"`
}

func (*HarnessResponse_Outputs) isHarnessResponse_Type() {}

func (*HarnessResponse_End) isHarnessResponse_Type() {}

// ExecRequest for executing.
type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // Unique conversation identifier
	Inputs         []*Message             `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`                                       // New inputs
	LastSeq        int32                  `protobuf:"varint,3,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`                     // Last sequence number seen by the client
	HarnessId      string                 `protobuf:"bytes,4,opt,name=harness_id,json=harnessId,proto3" json:"harness_id,omitempty"`                // Harness ID, empty selects the default harness
	HarnessConfig  []byte                 `protobuf:"bytes,5,opt,name=harness_config,json=harnessConfig,proto3" json:"harness_config,omitempty"`    // Per-request harness configuration (opaque JSON), if any
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_ax_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{9}
}

func (x *ExecRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ExecRequest) GetInputs() []*Message {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ExecRequest) GetLastSeq() int32 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *ExecRequest) GetHarnessId() string {
	if x != nil {
		return x.HarnessId
	}
	return ""
}

func (x *ExecRequest) GetHarnessConfig() []byte {
	if x != nil {
		return x.HarnessConfig
	}
	return nil
}

// ExecResponse contains the result of an execution.
type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*Message             `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"` // Output content
	Seq           int32                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`        // Seq of the outputs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_ax_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{10}
}

func (x *ExecResponse) GetOutputs() []*Message {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ExecResponse) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type DeleteConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteConversationRequest) Reset() {
	*x = DeleteConversationRequest{}
	mi := &file_proto_ax_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationRequest) ProtoMessage() {}

func (x *DeleteConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationRequest.ProtoReflect.Descriptor instead.
func (*DeleteConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type DeleteConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationResponse) Reset() {
	*x = DeleteConversationResponse{}
	mi := &file_proto_ax_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationResponse) ProtoMessage() {}

func (x *DeleteConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationResponse.ProtoReflect.Descriptor instead.
func (*DeleteConversationResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{12}
}

var File_proto_ax_proto protoreflect.FileDescriptor

const file_proto_ax_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ax.proto\x12\x02ax\x1a\x1cgoogle/protobuf/struct.proto\x1a\x13proto/content.proto\"D\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12%\n" +
	"\acontent\x18\x02 \x01(\v2\v.ax.ContentR\acontent\"\x90\x02\n" +
	"\x11ConversationEvent\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x05R\x03seq\x12\x17\n" +
	"\aexec_id\x18\x03 \x01(\tR\x06execId\x12\x1d\n" +
	"\n" +
	"harness_id\x18\x04 \x01(\tR\tharnessId\x12>\n" +
	"\x0eharness_config\x18\x05 \x01(\v2\x17.google.protobuf.StructR\rharnessConfig\x12'\n" +
	"\bmessages\x18\x06 \x03(\v2\v.ax.MessageR\bmessages\x12\x1f\n" +
	"\x05state\x18\a \x01(\x0e2\t.ax.StateR\x05state\"^\n" +
	"\fHarnessStart\x12%\n" +
	"\x0eharness_config\x18\x01 \x01(\fR\rharnessConfig\x12'\n" +
	"\bmessages\x18\x02 \x03(\v2\v.ax.MessageR\bmessages\"9\n" +
	"\rHarnessCancel\x12(\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x10.ax.CancelReasonR\x06reason\"\xb7\x01\n" +
	"\x0eHarnessRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"harness_id\x18\x02 \x01(\tR\tharnessId\x12(\n" +
	"\x05start\x18\x03 \x01(\v2\x10.ax.HarnessStartH\x00R\x05start\x12+\n" +
	"\x06cancel\x18\x04 \x01(\v2\x11.ax.HarnessCancelH\x00R\x06cancelB\x06\n" +
	"\x04type\"9\n" +
	"\x0eHarnessOutputs\x12'\n" +
	"\bmessages\x18\x01 \x03(\v2\v.ax.MessageR\bmessages\"=\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"N\n" +
	"\n" +
	"HarnessEnd\x12\x1f\n" +
	"\x05state\x18\x01 \x01(\x0e2\t.ax.StateR\x05state\x12\x1f\n" +
	"\x05error\x18\x02 \x01(\v2\t.ax.ErrorR\x05error\"\x96\x01\n" +
	"\x0fHarnessResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12.\n" +
	"\aoutputs\x18\x02 \x01(\v2\x12.ax.HarnessOutputsH\x00R\aoutputs\x12\"\n" +
	"\x03end\x18\x03 \x01(\v2\x0e.ax.HarnessEndH\x00R\x03endB\x06\n" +
	"\x04type\"\xbc\x01\n" +
	"\vExecRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12#\n" +
	"\x06inputs\x18\x02 \x03(\v2\v.ax.MessageR\x06inputs\x12\x19\n" +
	"\blast_seq\x18\x03 \x01(\x05R\alastSeq\x12\x1d\n" +
	"\n" +
	"harness_id\x18\x04 \x01(\tR\tharnessId\x12%\n" +
	"\x0eharness_config\x18\x05 \x01(\fR\rharnessConfig\"G\n" +
	"\fExecResponse\x12%\n" +
	"\aoutputs\x18\x01 \x03(\v2\v.ax.MessageR\aoutputs\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x05R\x03seq\"D\n" +
	"\x19DeleteConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"\x1c\n" +
	"\x1aDeleteConversationResponse*l\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_PENDING\x10\x01\x12\x10\n" +
	"\fSTATE_FAILED\x10\x02\x12\x13\n" +
	"\x0fSTATE_COMPLETED\x10\x03\x12\x12\n" +
	"\x0eSTATE_CANCELED\x10\x04*\x8c\x01\n" +
	"\fCancelReason\x12\x1d\n" +
	"\x19CANCEL_REASON_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCANCEL_REASON_USER_REQUESTED\x10\x01\x12\x19\n" +
	"\x15CANCEL_REASON_TIMEOUT\x10\x02\x12 \n" +
	"\x1cCANCEL_REASON_INTERNAL_ERROR\x10\x032H\n" +
	"\x0eHarnessService\x126\n" +
	"\aConnect\x12\x12.ax.HarnessRequest\x1a\x13.ax.HarnessResponse(\x010\x012@\n" +
	"\x11ControllerService\x12+\n" +
	"\x04Exec\x12\x0f.ax.ExecRequest\x1a\x10.ax.ExecResponse0\x012j\n" +
	"\x13ConversationService\x12S\n" +
	"\x12DeleteConversation\x12\x1d.ax.DeleteConversationRequest\x1a\x1e.ax.DeleteConversationResponseB\x1cZ\x1agithub.com/google/ax/protob\x06proto3"

var (
	file_proto_ax_proto_rawDescOnce sync.Once
	file_proto_ax_proto_rawDescData []byte
)

func file_proto_ax_proto_rawDescGZIP() []byte {
	file_proto_ax_proto_rawDescOnce.Do(func() {
		file_proto_ax_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ax_proto_rawDesc), len(file_proto_ax_proto_rawDesc)))
	})
	return file_proto_ax_proto_rawDescData
}

var file_proto_ax_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_ax_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_ax_proto_goTypes = []any{
	(State)(0),                         // 0: ax.State
	(CancelReason)(0),                  // 1: ax.CancelReason
	(*Message)(nil),                    // 2: ax.Message
	(*ConversationEvent)(nil),          // 3: ax.ConversationEvent
	(*HarnessStart)(nil),               // 4: ax.HarnessStart
	(*HarnessCancel)(nil),              // 5: ax.HarnessCancel
	(*HarnessRequest)(nil),             // 6: ax.HarnessRequest
	(*HarnessOutputs)(nil),             // 7: ax.HarnessOutputs
	(*Error)(nil),                      // 8: ax.Error
	(*HarnessEnd)(nil),                 // 9: ax.HarnessEnd
	(*HarnessResponse)(nil),            // 10: ax.HarnessResponse
	(*ExecRequest)(nil),                // 11: ax.ExecRequest
	(*ExecResponse)(nil),               // 12: ax.ExecResponse
	(*DeleteConversationRequest)(nil),  // 13: ax.DeleteConversationRequest
	(*DeleteConversationResponse)(nil), // 14: ax.DeleteConversationResponse
	(*Content)(nil),                    // 15: ax.Content
	(*structpb.Struct)(nil),            // 16: google.protobuf.Struct
}
var file_proto_ax_proto_depIdxs = []int32{
	15, // 0: ax.Message.content:type_name -> ax.Content
	16, // 1: ax.ConversationEvent.harness_config:type_name -> google.protobuf.Struct
	2,  // 2: ax.ConversationEvent.messages:type_name -> ax.Message
	0,  // 3: ax.ConversationEvent.state:type_name -> ax.State
	2,  // 4: ax.HarnessStart.messages:type_name -> ax.Message
	1,  // 5: ax.HarnessCancel.reason:type_name -> ax.CancelReason
	4,  // 6: ax.HarnessRequest.start:type_name -> ax.HarnessStart
	5,  // 7: ax.HarnessRequest.cancel:type_name -> ax.HarnessCancel
	2,  // 8: ax.HarnessOutputs.messages:type_name -> ax.Message
	0,  // 9: ax.HarnessEnd.state:type_name -> ax.State
	8,  // 10: ax.HarnessEnd.error:type_name -> ax.Error
	7,  // 11: ax.HarnessResponse.outputs:type_name -> ax.HarnessOutputs
	9,  // 12: ax.HarnessResponse.end:type_name -> ax.HarnessEnd
	2,  // 13: ax.ExecRequest.inputs:type_name -> ax.Message
	2,  // 14: ax.ExecResponse.outputs:type_name -> ax.Message
	6,  // 15: ax.HarnessService.Connect:input_type -> ax.HarnessRequest
	11, // 16: ax.ControllerService.Exec:input_type -> ax.ExecRequest
	13, // 17: ax.ConversationService.DeleteConversation:input_type -> ax.DeleteConversationRequest
	10, // 18: ax.HarnessService.Connect:output_type -> ax.HarnessResponse
	12, // 19: ax.ControllerService.Exec:output_type -> ax.ExecResponse
	14, // 20: ax.ConversationService.DeleteConversation:output_type -> ax.DeleteConversationResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_ax_proto_init() }
func file_proto_ax_proto_init() {
	if File_proto_ax_proto != nil {
		return
	}
	file_proto_content_proto_init()
	file_proto_ax_proto_msgTypes[4].OneofWrappers = []any{
		(*HarnessRequest_Start)(nil),
		(*HarnessRequest_Cancel)(nil),
	}
	file_proto_ax_proto_msgTypes[8].OneofWrappers = []any{
		(*HarnessResponse_Outputs)(nil),
		(*HarnessResponse_End)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ax_proto_rawDesc), len(file_proto_ax_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_ax_proto_goTypes,
		DependencyIndexes: file_proto_ax_proto_depIdxs,
		EnumInfos:         file_proto_ax_proto_enumTypes,
		MessageInfos:      file_proto_ax_proto_msgTypes,
	}.Build()
	File_proto_ax_proto = out.File
	file_proto_ax_proto_goTypes = nil
	file_proto_ax_proto_depIdxs = nil
}
