// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ax.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State represents the state of an execution
type State int32

const (
	State_STATE_UNSPECIFIED State = 0 // Unspecified state
	State_STATE_PENDING     State = 1
	State_STATE_FAILED      State = 2
	State_STATE_COMPLETED   State = 3
	State_STATE_CANCELED    State = 4
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_PENDING",
		2: "STATE_FAILED",
		3: "STATE_COMPLETED",
		4: "STATE_CANCELED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_PENDING":     1,
		"STATE_FAILED":      2,
		"STATE_COMPLETED":   3,
		"STATE_CANCELED":    4,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ax_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_ax_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{0}
}

// CancelReason explains why an in-flight execution is canceled.
type CancelReason int32

const (
	CancelReason_CANCEL_REASON_UNSPECIFIED    CancelReason = 0
	CancelReason_CANCEL_REASON_USER_REQUESTED CancelReason = 1
	CancelReason_CANCEL_REASON_TIMEOUT        CancelReason = 2
	CancelReason_CANCEL_REASON_INTERNAL_ERROR CancelReason = 3
)

// Enum value maps for CancelReason.
var (
	CancelReason_name = map[int32]string{
		0: "CANCEL_REASON_UNSPECIFIED",
		1: "CANCEL_REASON_USER_REQUESTED",
		2: "CANCEL_REASON_TIMEOUT",
		3: "CANCEL_REASON_INTERNAL_ERROR",
	}
	CancelReason_value = map[string]int32{
		"CANCEL_REASON_UNSPECIFIED":    0,
		"CANCEL_REASON_USER_REQUESTED": 1,
		"CANCEL_REASON_TIMEOUT":        2,
		"CANCEL_REASON_INTERNAL_ERROR": 3,
	}
)

func (x CancelReason) Enum() *CancelReason {
	p := new(CancelReason)
	*p = x
	return p
}

func (x CancelReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CancelReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ax_proto_enumTypes[1].Descriptor()
}

func (CancelReason) Type() protoreflect.EnumType {
	return &file_proto_ax_proto_enumTypes[1]
}

func (x CancelReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CancelReason.Descriptor instead.
func (CancelReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{1}
}

type AgentStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentConfig   []byte                 `protobuf:"bytes,2,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`
	Messages      []*Message             `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStart) Reset() {
	*x = AgentStart{}
	mi := &file_proto_ax_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStart) ProtoMessage() {}

func (x *AgentStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStart.ProtoReflect.Descriptor instead.
func (*AgentStart) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{0}
}

func (x *AgentStart) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStart) GetAgentConfig() []byte {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

func (x *AgentStart) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AgentOutputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentOutputs) Reset() {
	*x = AgentOutputs{}
	mi := &file_proto_ax_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentOutputs) ProtoMessage() {}

func (x *AgentOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentOutputs.ProtoReflect.Descriptor instead.
func (*AgentOutputs) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{1}
}

func (x *AgentOutputs) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AgentEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEnd) Reset() {
	*x = AgentEnd{}
	mi := &file_proto_ax_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEnd) ProtoMessage() {}

func (x *AgentEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEnd.ProtoReflect.Descriptor instead.
func (*AgentEnd) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{2}
}

type AgentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ExecId         string                 `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Start          *AgentStart            `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_proto_ax_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{3}
}

func (x *AgentRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AgentRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *AgentRequest) GetStart() *AgentStart {
	if x != nil {
		return x.Start
	}
	return nil
}

type AgentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ExecId         string                 `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*AgentResponse_Outputs
	//	*AgentResponse_End
	Type          isAgentResponse_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_proto_ax_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{4}
}

func (x *AgentResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AgentResponse) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *AgentResponse) GetType() isAgentResponse_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AgentResponse) GetOutputs() *AgentOutputs {
	if x != nil {
		if x, ok := x.Type.(*AgentResponse_Outputs); ok {
			return x.Outputs
		}
	}
	return nil
}

func (x *AgentResponse) GetEnd() *AgentEnd {
	if x != nil {
		if x, ok := x.Type.(*AgentResponse_End); ok {
			return x.End
		}
	}
	return nil
}

type isAgentResponse_Type interface {
	isAgentResponse_Type()
}

type AgentResponse_Outputs struct {
	Outputs *AgentOutputs `protobuf:"bytes,3,opt,name=outputs,proto3,oneof"`
}

type AgentResponse_End struct {
	End *AgentEnd `protobuf:"bytes,4,opt,name=end,proto3,oneof"`
}

func (*AgentResponse_Outputs) isAgentResponse_Type() {}

func (*AgentResponse_End) isAgentResponse_Type() {}

// Message is a message in the history.
type Message struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Role    string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`       // user, assistant, or model
	Content *Content               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // content of the message
	// If true, the message is stored only in the execution log
	// (for resumption) but not in the conversation history,
	// and not emitted to the client or any agent.
	InternalOnly  bool `protobuf:"varint,3,opt,name=internal_only,json=internalOnly,proto3" json:"internal_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_ax_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Message) GetInternalOnly() bool {
	if x != nil {
		return x.InternalOnly
	}
	return false
}

// A conversation is the historical session that consist of
// a number of execution. A conversation cannot be continued
// before the last execution is completed or failed.
type ConversationEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Seq            int32                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	ExecId         string                 `protobuf:"bytes,3,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Messages       []*Message             `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	State          State                  `protobuf:"varint,5,opt,name=state,proto3,enum=ax.State" json:"state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationEvent) Reset() {
	*x = ConversationEvent{}
	mi := &file_proto_ax_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationEvent) ProtoMessage() {}

func (x *ConversationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationEvent.ProtoReflect.Descriptor instead.
func (*ConversationEvent) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{6}
}

func (x *ConversationEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationEvent) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ConversationEvent) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ConversationEvent) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ConversationEvent) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

// ExecutionEvent is the entry in the event log. ExecutionEvents are used
// to record the actions taken place in the executor.
// The executor can replay the events for resumability.
type ExecutionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentConfig   []byte                 `protobuf:"bytes,3,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`
	Inputs        []*Message             `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []*Message             `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	State         State                  `protobuf:"varint,6,opt,name=state,proto3,enum=ax.State" json:"state,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionEvent) Reset() {
	*x = ExecutionEvent{}
	mi := &file_proto_ax_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionEvent) ProtoMessage() {}

func (x *ExecutionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionEvent.ProtoReflect.Descriptor instead.
func (*ExecutionEvent) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{7}
}

func (x *ExecutionEvent) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ExecutionEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecutionEvent) GetAgentConfig() []byte {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

func (x *ExecutionEvent) GetInputs() []*Message {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ExecutionEvent) GetOutputs() []*Message {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ExecutionEvent) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *ExecutionEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// HealthCheckRequest for agent health checks
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_ax_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{8}
}

// HealthCheckResponse contains agent health status
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_ax_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HarnessStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-execution harness configuration.
	HarnessConfig []byte     `protobuf:"bytes,1,opt,name=harness_config,json=harnessConfig,proto3" json:"harness_config,omitempty"`
	Messages      []*Message `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessStart) Reset() {
	*x = HarnessStart{}
	mi := &file_proto_ax_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessStart) ProtoMessage() {}

func (x *HarnessStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessStart.ProtoReflect.Descriptor instead.
func (*HarnessStart) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{10}
}

func (x *HarnessStart) GetHarnessConfig() []byte {
	if x != nil {
		return x.HarnessConfig
	}
	return nil
}

func (x *HarnessStart) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// HarnessCancel aborts the in-flight harness execution.
type HarnessCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        CancelReason           `protobuf:"varint,1,opt,name=reason,proto3,enum=ax.CancelReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessCancel) Reset() {
	*x = HarnessCancel{}
	mi := &file_proto_ax_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessCancel) ProtoMessage() {}

func (x *HarnessCancel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessCancel.ProtoReflect.Descriptor instead.
func (*HarnessCancel) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{11}
}

func (x *HarnessCancel) GetReason() CancelReason {
	if x != nil {
		return x.Reason
	}
	return CancelReason_CANCEL_REASON_UNSPECIFIED
}

type HarnessRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	HarnessId      string                 `protobuf:"bytes,2,opt,name=harness_id,json=harnessId,proto3" json:"harness_id,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*HarnessRequest_Start
	//	*HarnessRequest_Cancel
	Type          isHarnessRequest_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessRequest) Reset() {
	*x = HarnessRequest{}
	mi := &file_proto_ax_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessRequest) ProtoMessage() {}

func (x *HarnessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessRequest.ProtoReflect.Descriptor instead.
func (*HarnessRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{12}
}

func (x *HarnessRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *HarnessRequest) GetHarnessId() string {
	if x != nil {
		return x.HarnessId
	}
	return ""
}

func (x *HarnessRequest) GetType() isHarnessRequest_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *HarnessRequest) GetStart() *HarnessStart {
	if x != nil {
		if x, ok := x.Type.(*HarnessRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *HarnessRequest) GetCancel() *HarnessCancel {
	if x != nil {
		if x, ok := x.Type.(*HarnessRequest_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isHarnessRequest_Type interface {
	isHarnessRequest_Type()
}

type HarnessRequest_Start struct {
	Start *HarnessStart `protobuf:"bytes,3,opt,name=start,proto3,oneof"`
}

type HarnessRequest_Cancel struct {
	Cancel *HarnessCancel `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

func (*HarnessRequest_Start) isHarnessRequest_Type() {}

func (*HarnessRequest_Cancel) isHarnessRequest_Type() {}

type HarnessOutputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessOutputs) Reset() {
	*x = HarnessOutputs{}
	mi := &file_proto_ax_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessOutputs) ProtoMessage() {}

func (x *HarnessOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessOutputs.ProtoReflect.Descriptor instead.
func (*HarnessOutputs) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{13}
}

func (x *HarnessOutputs) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type HarnessEnd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Terminal state for the harness execution.
	State State `protobuf:"varint,1,opt,name=state,proto3,enum=ax.State" json:"state,omitempty"`
	// Optional error message.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessEnd) Reset() {
	*x = HarnessEnd{}
	mi := &file_proto_ax_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessEnd) ProtoMessage() {}

func (x *HarnessEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessEnd.ProtoReflect.Descriptor instead.
func (*HarnessEnd) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{14}
}

func (x *HarnessEnd) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *HarnessEnd) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HarnessResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*HarnessResponse_Outputs
	//	*HarnessResponse_End
	Type          isHarnessResponse_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessResponse) Reset() {
	*x = HarnessResponse{}
	mi := &file_proto_ax_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessResponse) ProtoMessage() {}

func (x *HarnessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessResponse.ProtoReflect.Descriptor instead.
func (*HarnessResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{15}
}

func (x *HarnessResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *HarnessResponse) GetType() isHarnessResponse_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *HarnessResponse) GetOutputs() *HarnessOutputs {
	if x != nil {
		if x, ok := x.Type.(*HarnessResponse_Outputs); ok {
			return x.Outputs
		}
	}
	return nil
}

func (x *HarnessResponse) GetEnd() *HarnessEnd {
	if x != nil {
		if x, ok := x.Type.(*HarnessResponse_End); ok {
			return x.End
		}
	}
	return nil
}

type isHarnessResponse_Type interface {
	isHarnessResponse_Type()
}

type HarnessResponse_Outputs struct {
	Outputs *HarnessOutputs `protobuf:"bytes,2,opt,name=outputs,proto3,oneof"`
}

type HarnessResponse_End struct {
	End *HarnessEnd `protobuf:"bytes,3,opt,name=end,proto3,oneof"`
}

func (*HarnessResponse_Outputs) isHarnessResponse_Type() {}

func (*HarnessResponse_End) isHarnessResponse_Type() {}

// ExecRequest for executing.
type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // Unique conversation identifier
	Inputs         []*Message             `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`                                       // New inputs
	LastSeq        int32                  `protobuf:"varint,3,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`                     // Last sequence number seen by the client
	AgentId        string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                      // Agent ID, if empty planner is used
	AgentConfig    []byte                 `protobuf:"bytes,5,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`          // Agent configuration if any
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_ax_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{16}
}

func (x *ExecRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ExecRequest) GetInputs() []*Message {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ExecRequest) GetLastSeq() int32 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *ExecRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecRequest) GetAgentConfig() []byte {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

// ExecResponse contains the result of an execution.
type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*Message             `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"` // Output content
	Seq           int32                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`        // Seq of the outputs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_ax_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{17}
}

func (x *ExecResponse) GetOutputs() []*Message {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ExecResponse) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type DeleteConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteConversationRequest) Reset() {
	*x = DeleteConversationRequest{}
	mi := &file_proto_ax_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationRequest) ProtoMessage() {}

func (x *DeleteConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationRequest.ProtoReflect.Descriptor instead.
func (*DeleteConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type DeleteConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationResponse) Reset() {
	*x = DeleteConversationResponse{}
	mi := &file_proto_ax_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationResponse) ProtoMessage() {}

func (x *DeleteConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationResponse.ProtoReflect.Descriptor instead.
func (*DeleteConversationResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{19}
}

type ForkConversationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: The source conversation ID to fork from.
	SrcConversationId string `protobuf:"bytes,1,opt,name=src_conversation_id,json=srcConversationId,proto3" json:"src_conversation_id,omitempty"`
	// Optional: The sequence number to fork from.
	// Defaults to the latest sequence if not set or set to 0.
	SrcSeq int32 `protobuf:"varint,2,opt,name=src_seq,json=srcSeq,proto3" json:"src_seq,omitempty"` // TODO(jbd): Replace this with snapshot_id.
	// Optional: The destination conversation ID.
	// Generates a new UUID if not provided.
	DestConversationId string `protobuf:"bytes,3,opt,name=dest_conversation_id,json=destConversationId,proto3" json:"dest_conversation_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ForkConversationRequest) Reset() {
	*x = ForkConversationRequest{}
	mi := &file_proto_ax_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkConversationRequest) ProtoMessage() {}

func (x *ForkConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkConversationRequest.ProtoReflect.Descriptor instead.
func (*ForkConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{20}
}

func (x *ForkConversationRequest) GetSrcConversationId() string {
	if x != nil {
		return x.SrcConversationId
	}
	return ""
}

func (x *ForkConversationRequest) GetSrcSeq() int32 {
	if x != nil {
		return x.SrcSeq
	}
	return 0
}

func (x *ForkConversationRequest) GetDestConversationId() string {
	if x != nil {
		return x.DestConversationId
	}
	return ""
}

type ForkConversationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // The ID of the new conversation
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForkConversationResponse) Reset() {
	*x = ForkConversationResponse{}
	mi := &file_proto_ax_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkConversationResponse) ProtoMessage() {}

func (x *ForkConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkConversationResponse.ProtoReflect.Descriptor instead.
func (*ForkConversationResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{21}
}

func (x *ForkConversationResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

var File_proto_ax_proto protoreflect.FileDescriptor

const file_proto_ax_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ax.proto\x12\x02ax\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13proto/content.proto\"s\n" +
	"\n" +
	"AgentStart\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\fagent_config\x18\x02 \x01(\fR\vagentConfig\x12'\n" +
	"\bmessages\x18\x03 \x03(\v2\v.ax.MessageR\bmessages\"7\n" +
	"\fAgentOutputs\x12'\n" +
	"\bmessages\x18\x01 \x03(\v2\v.ax.MessageR\bmessages\"\n" +
	"\n" +
	"\bAgentEnd\"v\n" +
	"\fAgentRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\x12$\n" +
	"\x05start\x18\x03 \x01(\v2\x0e.ax.AgentStartR\x05start\"\xa9\x01\n" +
	"\rAgentResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\x12,\n" +
	"\aoutputs\x18\x03 \x01(\v2\x10.ax.AgentOutputsH\x00R\aoutputs\x12 \n" +
	"\x03end\x18\x04 \x01(\v2\f.ax.AgentEndH\x00R\x03endB\x06\n" +
	"\x04type\"i\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12%\n" +
	"\acontent\x18\x02 \x01(\v2\v.ax.ContentR\acontent\x12#\n" +
	"\rinternal_only\x18\x03 \x01(\bR\finternalOnly\"\xb1\x01\n" +
	"\x11ConversationEvent\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x05R\x03seq\x12\x17\n" +
	"\aexec_id\x18\x03 \x01(\tR\x06execId\x12'\n" +
	"\bmessages\x18\x04 \x03(\v2\v.ax.MessageR\bmessages\x12\x1f\n" +
	"\x05state\x18\x05 \x01(\x0e2\t.ax.StateR\x05state\"\x8e\x02\n" +
	"\x0eExecutionEvent\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12!\n" +
	"\fagent_config\x18\x03 \x01(\fR\vagentConfig\x12#\n" +
	"\x06inputs\x18\x04 \x03(\v2\v.ax.MessageR\x06inputs\x12%\n" +
	"\aoutputs\x18\x05 \x03(\v2\v.ax.MessageR\aoutputs\x12\x1f\n" +
	"\x05state\x18\x06 \x01(\x0e2\t.ax.StateR\x05state\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"^\n" +
	"\fHarnessStart\x12%\n" +
	"\x0eharness_config\x18\x01 \x01(\fR\rharnessConfig\x12'\n" +
	"\bmessages\x18\x02 \x03(\v2\v.ax.MessageR\bmessages\"9\n" +
	"\rHarnessCancel\x12(\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x10.ax.CancelReasonR\x06reason\"\xb7\x01\n" +
	"\x0eHarnessRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"harness_id\x18\x02 \x01(\tR\tharnessId\x12(\n" +
	"\x05start\x18\x03 \x01(\v2\x10.ax.HarnessStartH\x00R\x05start\x12+\n" +
	"\x06cancel\x18\x04 \x01(\v2\x11.ax.HarnessCancelH\x00R\x06cancelB\x06\n" +
	"\x04type\"9\n" +
	"\x0eHarnessOutputs\x12'\n" +
	"\bmessages\x18\x01 \x03(\v2\v.ax.MessageR\bmessages\"R\n" +
	"\n" +
	"HarnessEnd\x12\x1f\n" +
	"\x05state\x18\x01 \x01(\x0e2\t.ax.StateR\x05state\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x96\x01\n" +
	"\x0fHarnessResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12.\n" +
	"\aoutputs\x18\x02 \x01(\v2\x12.ax.HarnessOutputsH\x00R\aoutputs\x12\"\n" +
	"\x03end\x18\x03 \x01(\v2\x0e.ax.HarnessEndH\x00R\x03endB\x06\n" +
	"\x04type\"\xb4\x01\n" +
	"\vExecRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12#\n" +
	"\x06inputs\x18\x02 \x03(\v2\v.ax.MessageR\x06inputs\x12\x19\n" +
	"\blast_seq\x18\x03 \x01(\x05R\alastSeq\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12!\n" +
	"\fagent_config\x18\x05 \x01(\fR\vagentConfig\"G\n" +
	"\fExecResponse\x12%\n" +
	"\aoutputs\x18\x01 \x03(\v2\v.ax.MessageR\aoutputs\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x05R\x03seq\"D\n" +
	"\x19DeleteConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"\x1c\n" +
	"\x1aDeleteConversationResponse\"\x94\x01\n" +
	"\x17ForkConversationRequest\x12.\n" +
	"\x13src_conversation_id\x18\x01 \x01(\tR\x11srcConversationId\x12\x17\n" +
	"\asrc_seq\x18\x02 \x01(\x05R\x06srcSeq\x120\n" +
	"\x14dest_conversation_id\x18\x03 \x01(\tR\x12destConversationId\"C\n" +
	"\x18ForkConversationResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId*l\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_PENDING\x10\x01\x12\x10\n" +
	"\fSTATE_FAILED\x10\x02\x12\x13\n" +
	"\x0fSTATE_COMPLETED\x10\x03\x12\x12\n" +
	"\x0eSTATE_CANCELED\x10\x04*\x8c\x01\n" +
	"\fCancelReason\x12\x1d\n" +
	"\x19CANCEL_REASON_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCANCEL_REASON_USER_REQUESTED\x10\x01\x12\x19\n" +
	"\x15CANCEL_REASON_TIMEOUT\x10\x02\x12 \n" +
	"\x1cCANCEL_REASON_INTERNAL_ERROR\x10\x032\x80\x01\n" +
	"\fAgentService\x120\n" +
	"\aConnect\x12\x10.ax.AgentRequest\x1a\x11.ax.AgentResponse0\x01\x12>\n" +
	"\vHealthCheck\x12\x16.ax.HealthCheckRequest\x1a\x17.ax.HealthCheckResponse2H\n" +
	"\x0eHarnessService\x126\n" +
	"\aConnect\x12\x12.ax.HarnessRequest\x1a\x13.ax.HarnessResponse(\x010\x012@\n" +
	"\x11ControllerService\x12+\n" +
	"\x04Exec\x12\x0f.ax.ExecRequest\x1a\x10.ax.ExecResponse0\x012\xb9\x01\n" +
	"\x13ConversationService\x12S\n" +
	"\x12DeleteConversation\x12\x1d.ax.DeleteConversationRequest\x1a\x1e.ax.DeleteConversationResponse\x12M\n" +
	"\x10ForkConversation\x12\x1b.ax.ForkConversationRequest\x1a\x1c.ax.ForkConversationResponseB\x1cZ\x1agithub.com/google/ax/protob\x06proto3"

var (
	file_proto_ax_proto_rawDescOnce sync.Once
	file_proto_ax_proto_rawDescData []byte
)

func file_proto_ax_proto_rawDescGZIP() []byte {
	file_proto_ax_proto_rawDescOnce.Do(func() {
		file_proto_ax_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ax_proto_rawDesc), len(file_proto_ax_proto_rawDesc)))
	})
	return file_proto_ax_proto_rawDescData
}

var file_proto_ax_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_ax_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_ax_proto_goTypes = []any{
	(State)(0),                         // 0: ax.State
	(CancelReason)(0),                  // 1: ax.CancelReason
	(*AgentStart)(nil),                 // 2: ax.AgentStart
	(*AgentOutputs)(nil),               // 3: ax.AgentOutputs
	(*AgentEnd)(nil),                   // 4: ax.AgentEnd
	(*AgentRequest)(nil),               // 5: ax.AgentRequest
	(*AgentResponse)(nil),              // 6: ax.AgentResponse
	(*Message)(nil),                    // 7: ax.Message
	(*ConversationEvent)(nil),          // 8: ax.ConversationEvent
	(*ExecutionEvent)(nil),             // 9: ax.ExecutionEvent
	(*HealthCheckRequest)(nil),         // 10: ax.HealthCheckRequest
	(*HealthCheckResponse)(nil),        // 11: ax.HealthCheckResponse
	(*HarnessStart)(nil),               // 12: ax.HarnessStart
	(*HarnessCancel)(nil),              // 13: ax.HarnessCancel
	(*HarnessRequest)(nil),             // 14: ax.HarnessRequest
	(*HarnessOutputs)(nil),             // 15: ax.HarnessOutputs
	(*HarnessEnd)(nil),                 // 16: ax.HarnessEnd
	(*HarnessResponse)(nil),            // 17: ax.HarnessResponse
	(*ExecRequest)(nil),                // 18: ax.ExecRequest
	(*ExecResponse)(nil),               // 19: ax.ExecResponse
	(*DeleteConversationRequest)(nil),  // 20: ax.DeleteConversationRequest
	(*DeleteConversationResponse)(nil), // 21: ax.DeleteConversationResponse
	(*ForkConversationRequest)(nil),    // 22: ax.ForkConversationRequest
	(*ForkConversationResponse)(nil),   // 23: ax.ForkConversationResponse
	(*Content)(nil),                    // 24: ax.Content
	(*timestamppb.Timestamp)(nil),      // 25: google.protobuf.Timestamp
}
var file_proto_ax_proto_depIdxs = []int32{
	7,  // 0: ax.AgentStart.messages:type_name -> ax.Message
	7,  // 1: ax.AgentOutputs.messages:type_name -> ax.Message
	2,  // 2: ax.AgentRequest.start:type_name -> ax.AgentStart
	3,  // 3: ax.AgentResponse.outputs:type_name -> ax.AgentOutputs
	4,  // 4: ax.AgentResponse.end:type_name -> ax.AgentEnd
	24, // 5: ax.Message.content:type_name -> ax.Content
	7,  // 6: ax.ConversationEvent.messages:type_name -> ax.Message
	0,  // 7: ax.ConversationEvent.state:type_name -> ax.State
	7,  // 8: ax.ExecutionEvent.inputs:type_name -> ax.Message
	7,  // 9: ax.ExecutionEvent.outputs:type_name -> ax.Message
	0,  // 10: ax.ExecutionEvent.state:type_name -> ax.State
	25, // 11: ax.ExecutionEvent.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 12: ax.HarnessStart.messages:type_name -> ax.Message
	1,  // 13: ax.HarnessCancel.reason:type_name -> ax.CancelReason
	12, // 14: ax.HarnessRequest.start:type_name -> ax.HarnessStart
	13, // 15: ax.HarnessRequest.cancel:type_name -> ax.HarnessCancel
	7,  // 16: ax.HarnessOutputs.messages:type_name -> ax.Message
	0,  // 17: ax.HarnessEnd.state:type_name -> ax.State
	15, // 18: ax.HarnessResponse.outputs:type_name -> ax.HarnessOutputs
	16, // 19: ax.HarnessResponse.end:type_name -> ax.HarnessEnd
	7,  // 20: ax.ExecRequest.inputs:type_name -> ax.Message
	7,  // 21: ax.ExecResponse.outputs:type_name -> ax.Message
	5,  // 22: ax.AgentService.Connect:input_type -> ax.AgentRequest
	10, // 23: ax.AgentService.HealthCheck:input_type -> ax.HealthCheckRequest
	14, // 24: ax.HarnessService.Connect:input_type -> ax.HarnessRequest
	18, // 25: ax.ControllerService.Exec:input_type -> ax.ExecRequest
	20, // 26: ax.ConversationService.DeleteConversation:input_type -> ax.DeleteConversationRequest
	22, // 27: ax.ConversationService.ForkConversation:input_type -> ax.ForkConversationRequest
	6,  // 28: ax.AgentService.Connect:output_type -> ax.AgentResponse
	11, // 29: ax.AgentService.HealthCheck:output_type -> ax.HealthCheckResponse
	17, // 30: ax.HarnessService.Connect:output_type -> ax.HarnessResponse
	19, // 31: ax.ControllerService.Exec:output_type -> ax.ExecResponse
	21, // 32: ax.ConversationService.DeleteConversation:output_type -> ax.DeleteConversationResponse
	23, // 33: ax.ConversationService.ForkConversation:output_type -> ax.ForkConversationResponse
	28, // [28:34] is the sub-list for method output_type
	22, // [22:28] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_ax_proto_init() }
func file_proto_ax_proto_init() {
	if File_proto_ax_proto != nil {
		return
	}
	file_proto_content_proto_init()
	file_proto_ax_proto_msgTypes[4].OneofWrappers = []any{
		(*AgentResponse_Outputs)(nil),
		(*AgentResponse_End)(nil),
	}
	file_proto_ax_proto_msgTypes[12].OneofWrappers = []any{
		(*HarnessRequest_Start)(nil),
		(*HarnessRequest_Cancel)(nil),
	}
	file_proto_ax_proto_msgTypes[15].OneofWrappers = []any{
		(*HarnessResponse_Outputs)(nil),
		(*HarnessResponse_End)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ax_proto_rawDesc), len(file_proto_ax_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_ax_proto_goTypes,
		DependencyIndexes: file_proto_ax_proto_depIdxs,
		EnumInfos:         file_proto_ax_proto_enumTypes,
		MessageInfos:      file_proto_ax_proto_msgTypes,
	}.Build()
	File_proto_ax_proto = out.File
	file_proto_ax_proto_goTypes = nil
	file_proto_ax_proto_depIdxs = nil
}
