// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/ax.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State represents the state of an execution
type State int32

const (
	State_STATE_UNSPECIFIED State = 0 // Unspecified state
	State_STATE_PENDING     State = 1
	State_STATE_FAILED      State = 2
	State_STATE_COMPLETED   State = 3
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_PENDING",
		2: "STATE_FAILED",
		3: "STATE_COMPLETED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_PENDING":     1,
		"STATE_FAILED":      2,
		"STATE_COMPLETED":   3,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ax_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_ax_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{0}
}

type AgentStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Config        *anypb.Any             `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Messages      []*Message             `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStart) Reset() {
	*x = AgentStart{}
	mi := &file_proto_ax_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStart) ProtoMessage() {}

func (x *AgentStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStart.ProtoReflect.Descriptor instead.
func (*AgentStart) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{0}
}

func (x *AgentStart) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStart) GetConfig() *anypb.Any {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AgentStart) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AgentOutputs struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Messages []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// If true, these outputs are stored only in the execution log
	// (for resumption) and are not emitted to the client or stored
	// in the conversation history.
	InternalOnly  bool `protobuf:"varint,2,opt,name=internal_only,json=internalOnly,proto3" json:"internal_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentOutputs) Reset() {
	*x = AgentOutputs{}
	mi := &file_proto_ax_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentOutputs) ProtoMessage() {}

func (x *AgentOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentOutputs.ProtoReflect.Descriptor instead.
func (*AgentOutputs) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{1}
}

func (x *AgentOutputs) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *AgentOutputs) GetInternalOnly() bool {
	if x != nil {
		return x.InternalOnly
	}
	return false
}

type AgentMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ExecId string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentMessage_Start
	//	*AgentMessage_Outputs
	Msg           isAgentMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_ax_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *AgentMessage) GetMsg() isAgentMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentMessage) GetStart() *AgentStart {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *AgentMessage) GetOutputs() *AgentOutputs {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Outputs); ok {
			return x.Outputs
		}
	}
	return nil
}

type isAgentMessage_Msg interface {
	isAgentMessage_Msg()
}

type AgentMessage_Start struct {
	Start *AgentStart `protobuf:"bytes,2,opt,name=start,proto3,oneof"`
}

type AgentMessage_Outputs struct {
	Outputs *AgentOutputs `protobuf:"bytes,3,opt,name=outputs,proto3,oneof"`
}

func (*AgentMessage_Start) isAgentMessage_Msg() {}

func (*AgentMessage_Outputs) isAgentMessage_Msg() {}

// Message is a message in the history.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`       // user, assistant, or model
	Content       *Content               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // content of the message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_ax_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

// A conversation is the historical session that consist of
// a number of execution. A conversation cannot be continued
// before the last execution is completed or failed.
type ConversationEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Seq            int32                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	ExecId         string                 `protobuf:"bytes,3,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Messages       []*Message             `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	State          State                  `protobuf:"varint,5,opt,name=state,proto3,enum=proto.State" json:"state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationEvent) Reset() {
	*x = ConversationEvent{}
	mi := &file_proto_ax_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationEvent) ProtoMessage() {}

func (x *ConversationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationEvent.ProtoReflect.Descriptor instead.
func (*ConversationEvent) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{4}
}

func (x *ConversationEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationEvent) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ConversationEvent) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ConversationEvent) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ConversationEvent) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

// ExecutionEvent is the entry in the event log. ExecutionEvents are used
// to record the actions taken place in the executor.
// The executor can replay the events for resumability.
type ExecutionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentConfig   *anypb.Any             `protobuf:"bytes,3,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`
	Inputs        []*Message             `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []*Message             `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	State         State                  `protobuf:"varint,6,opt,name=state,proto3,enum=proto.State" json:"state,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionEvent) Reset() {
	*x = ExecutionEvent{}
	mi := &file_proto_ax_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionEvent) ProtoMessage() {}

func (x *ExecutionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionEvent.ProtoReflect.Descriptor instead.
func (*ExecutionEvent) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{5}
}

func (x *ExecutionEvent) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ExecutionEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecutionEvent) GetAgentConfig() *anypb.Any {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

func (x *ExecutionEvent) GetInputs() []*Message {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ExecutionEvent) GetOutputs() []*Message {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ExecutionEvent) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *ExecutionEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// HealthCheckRequest for agent health checks
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_ax_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{6}
}

// HealthCheckResponse contains agent health status
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_ax_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ExecRequest for executing.
type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // Unique conversation identifier
	Inputs         []*Message             `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`                                       // New inputs
	LastSeenSeq    int32                  `protobuf:"varint,3,opt,name=last_seen_seq,json=lastSeenSeq,proto3" json:"last_seen_seq,omitempty"`       // Last sequence number seen by the client
	AgentId        string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                      // Agent ID, if empty planner is used
	AgentConfig    *anypb.Any             `protobuf:"bytes,5,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`          // Agent configuration if any
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_ax_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{8}
}

func (x *ExecRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ExecRequest) GetInputs() []*Message {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ExecRequest) GetLastSeenSeq() int32 {
	if x != nil {
		return x.LastSeenSeq
	}
	return 0
}

func (x *ExecRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecRequest) GetAgentConfig() *anypb.Any {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

// ExecResponse contains the result of an execution.
type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*Message             `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"` // Output content
	Seq           int32                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`        // Seq of the outputs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_ax_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{9}
}

func (x *ExecResponse) GetOutputs() []*Message {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ExecResponse) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type RemoteAgentConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // gRPC address for remote agents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteAgentConfig) Reset() {
	*x = RemoteAgentConfig{}
	mi := &file_proto_ax_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteAgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteAgentConfig) ProtoMessage() {}

func (x *RemoteAgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteAgentConfig.ProtoReflect.Descriptor instead.
func (*RemoteAgentConfig) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{10}
}

func (x *RemoteAgentConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// RegisterAgentRequest for registering an agent
type RegisterAgentRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AgentId     string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // Human-readable name for the agent
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // Description of agent capabilities
	Metadata    map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Config:
	//
	//	*RegisterAgentRequest_Remote
	Config        isRegisterAgentRequest_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_proto_ax_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAgentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterAgentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterAgentRequest) GetConfig() isRegisterAgentRequest_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RegisterAgentRequest) GetRemote() *RemoteAgentConfig {
	if x != nil {
		if x, ok := x.Config.(*RegisterAgentRequest_Remote); ok {
			return x.Remote
		}
	}
	return nil
}

type isRegisterAgentRequest_Config interface {
	isRegisterAgentRequest_Config()
}

type RegisterAgentRequest_Remote struct {
	Remote *RemoteAgentConfig `protobuf:"bytes,5,opt,name=remote,proto3,oneof"`
}

func (*RegisterAgentRequest_Remote) isRegisterAgentRequest_Config() {}

// RegisterAgentResponse contains registration result
type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_proto_ax_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterAgentResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type ListRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_ax_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{13}
}

func (x *ListRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ConversationEvent   `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"` // TODO: Do we need pagination?
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_ax_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{14}
}

func (x *ListResponse) GetEvents() []*ConversationEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type DeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_ax_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_ax_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{16}
}

type ForkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkRequest) Reset() {
	*x = ForkRequest{}
	mi := &file_proto_ax_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkRequest) ProtoMessage() {}

func (x *ForkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkRequest.ProtoReflect.Descriptor instead.
func (*ForkRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{17}
}

type ForkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkResponse) Reset() {
	*x = ForkResponse{}
	mi := &file_proto_ax_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkResponse) ProtoMessage() {}

func (x *ForkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkResponse.ProtoReflect.Descriptor instead.
func (*ForkResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{18}
}

// GeminiConfig is the configuration for a Gemini agent.
type GeminiConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`                                   // e.g. "gemini-3-flash-preview"
	SystemPrompt  string                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"` // System prompt for the agent
	MaxTokens     int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`         // Maximum number of tokens to generate
	Timeout       *durationpb.Duration   `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`                               // e.g. "10s"
	Tools         []string               `protobuf:"bytes,5,rep,name=tools,proto3" json:"tools,omitempty"`                                   // List of enabled tools (e.g. "google_search")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeminiConfig) Reset() {
	*x = GeminiConfig{}
	mi := &file_proto_ax_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeminiConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeminiConfig) ProtoMessage() {}

func (x *GeminiConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeminiConfig.ProtoReflect.Descriptor instead.
func (*GeminiConfig) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{19}
}

func (x *GeminiConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GeminiConfig) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *GeminiConfig) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *GeminiConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *GeminiConfig) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

var File_proto_ax_proto protoreflect.FileDescriptor

const file_proto_ax_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ax.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x13proto/content.proto\"\x81\x01\n" +
	"\n" +
	"AgentStart\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12,\n" +
	"\x06config\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x06config\x12*\n" +
	"\bmessages\x18\x03 \x03(\v2\x0e.proto.MessageR\bmessages\"_\n" +
	"\fAgentOutputs\x12*\n" +
	"\bmessages\x18\x01 \x03(\v2\x0e.proto.MessageR\bmessages\x12#\n" +
	"\rinternal_only\x18\x02 \x01(\bR\finternalOnly\"\x8a\x01\n" +
	"\fAgentMessage\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12)\n" +
	"\x05start\x18\x02 \x01(\v2\x11.proto.AgentStartH\x00R\x05start\x12/\n" +
	"\aoutputs\x18\x03 \x01(\v2\x13.proto.AgentOutputsH\x00R\aoutputsB\x05\n" +
	"\x03msg\"G\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12(\n" +
	"\acontent\x18\x02 \x01(\v2\x0e.proto.ContentR\acontent\"\xb7\x01\n" +
	"\x11ConversationEvent\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x05R\x03seq\x12\x17\n" +
	"\aexec_id\x18\x03 \x01(\tR\x06execId\x12*\n" +
	"\bmessages\x18\x04 \x03(\v2\x0e.proto.MessageR\bmessages\x12\"\n" +
	"\x05state\x18\x05 \x01(\x0e2\f.proto.StateR\x05state\"\xad\x02\n" +
	"\x0eExecutionEvent\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x127\n" +
	"\fagent_config\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\vagentConfig\x12&\n" +
	"\x06inputs\x18\x04 \x03(\v2\x0e.proto.MessageR\x06inputs\x12(\n" +
	"\aoutputs\x18\x05 \x03(\v2\x0e.proto.MessageR\aoutputs\x12\"\n" +
	"\x05state\x18\x06 \x01(\x0e2\f.proto.StateR\x05state\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd6\x01\n" +
	"\vExecRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12&\n" +
	"\x06inputs\x18\x02 \x03(\v2\x0e.proto.MessageR\x06inputs\x12\"\n" +
	"\rlast_seen_seq\x18\x03 \x01(\x05R\vlastSeenSeq\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x127\n" +
	"\fagent_config\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\vagentConfig\"J\n" +
	"\fExecResponse\x12(\n" +
	"\aoutputs\x18\x01 \x03(\v2\x0e.proto.MessageR\aoutputs\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x05R\x03seq\"-\n" +
	"\x11RemoteAgentConfig\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\xa9\x02\n" +
	"\x14RegisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12E\n" +
	"\bmetadata\x18\x04 \x03(\v2).proto.RegisterAgentRequest.MetadataEntryR\bmetadata\x122\n" +
	"\x06remote\x18\x05 \x01(\v2\x18.proto.RemoteAgentConfigH\x00R\x06remote\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06config\"1\n" +
	"\x15RegisterAgentResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\"6\n" +
	"\vListRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"@\n" +
	"\fListResponse\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.proto.ConversationEventR\x06events\"8\n" +
	"\rDeleteRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"\x10\n" +
	"\x0eDeleteResponse\"\r\n" +
	"\vForkRequest\"\x0e\n" +
	"\fForkResponse\"\xb3\x01\n" +
	"\fGeminiConfig\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x14\n" +
	"\x05tools\x18\x05 \x03(\tR\x05tools*X\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_PENDING\x10\x01\x12\x10\n" +
	"\fSTATE_FAILED\x10\x02\x12\x13\n" +
	"\x0fSTATE_COMPLETED\x10\x032\x8f\x01\n" +
	"\x0eAXAgentService\x127\n" +
	"\aConnect\x12\x13.proto.AgentMessage\x1a\x13.proto.AgentMessage(\x010\x01\x12D\n" +
	"\vHealthCheck\x12\x19.proto.HealthCheckRequest\x1a\x1a.proto.HealthCheckResponse2\x8a\x01\n" +
	"\tAXService\x121\n" +
	"\x04Exec\x12\x12.proto.ExecRequest\x1a\x13.proto.ExecResponse0\x01\x12J\n" +
	"\rRegisterAgent\x12\x1b.proto.RegisterAgentRequest\x1a\x1c.proto.RegisterAgentResponse2\xac\x01\n" +
	"\x11AXEventLogService\x12/\n" +
	"\x04List\x12\x12.proto.ListRequest\x1a\x13.proto.ListResponse\x125\n" +
	"\x06Delete\x12\x14.proto.DeleteRequest\x1a\x15.proto.DeleteResponse\x12/\n" +
	"\x04Fork\x12\x12.proto.ForkRequest\x1a\x13.proto.ForkResponseB\x1cZ\x1agithub.com/google/ax/protob\x06proto3"

var (
	file_proto_ax_proto_rawDescOnce sync.Once
	file_proto_ax_proto_rawDescData []byte
)

func file_proto_ax_proto_rawDescGZIP() []byte {
	file_proto_ax_proto_rawDescOnce.Do(func() {
		file_proto_ax_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ax_proto_rawDesc), len(file_proto_ax_proto_rawDesc)))
	})
	return file_proto_ax_proto_rawDescData
}

var file_proto_ax_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ax_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_ax_proto_goTypes = []any{
	(State)(0),                    // 0: proto.State
	(*AgentStart)(nil),            // 1: proto.AgentStart
	(*AgentOutputs)(nil),          // 2: proto.AgentOutputs
	(*AgentMessage)(nil),          // 3: proto.AgentMessage
	(*Message)(nil),               // 4: proto.Message
	(*ConversationEvent)(nil),     // 5: proto.ConversationEvent
	(*ExecutionEvent)(nil),        // 6: proto.ExecutionEvent
	(*HealthCheckRequest)(nil),    // 7: proto.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 8: proto.HealthCheckResponse
	(*ExecRequest)(nil),           // 9: proto.ExecRequest
	(*ExecResponse)(nil),          // 10: proto.ExecResponse
	(*RemoteAgentConfig)(nil),     // 11: proto.RemoteAgentConfig
	(*RegisterAgentRequest)(nil),  // 12: proto.RegisterAgentRequest
	(*RegisterAgentResponse)(nil), // 13: proto.RegisterAgentResponse
	(*ListRequest)(nil),           // 14: proto.ListRequest
	(*ListResponse)(nil),          // 15: proto.ListResponse
	(*DeleteRequest)(nil),         // 16: proto.DeleteRequest
	(*DeleteResponse)(nil),        // 17: proto.DeleteResponse
	(*ForkRequest)(nil),           // 18: proto.ForkRequest
	(*ForkResponse)(nil),          // 19: proto.ForkResponse
	(*GeminiConfig)(nil),          // 20: proto.GeminiConfig
	nil,                           // 21: proto.RegisterAgentRequest.MetadataEntry
	(*anypb.Any)(nil),             // 22: google.protobuf.Any
	(*Content)(nil),               // 23: proto.Content
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 25: google.protobuf.Duration
}
var file_proto_ax_proto_depIdxs = []int32{
	22, // 0: proto.AgentStart.config:type_name -> google.protobuf.Any
	4,  // 1: proto.AgentStart.messages:type_name -> proto.Message
	4,  // 2: proto.AgentOutputs.messages:type_name -> proto.Message
	1,  // 3: proto.AgentMessage.start:type_name -> proto.AgentStart
	2,  // 4: proto.AgentMessage.outputs:type_name -> proto.AgentOutputs
	23, // 5: proto.Message.content:type_name -> proto.Content
	4,  // 6: proto.ConversationEvent.messages:type_name -> proto.Message
	0,  // 7: proto.ConversationEvent.state:type_name -> proto.State
	22, // 8: proto.ExecutionEvent.agent_config:type_name -> google.protobuf.Any
	4,  // 9: proto.ExecutionEvent.inputs:type_name -> proto.Message
	4,  // 10: proto.ExecutionEvent.outputs:type_name -> proto.Message
	0,  // 11: proto.ExecutionEvent.state:type_name -> proto.State
	24, // 12: proto.ExecutionEvent.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 13: proto.ExecRequest.inputs:type_name -> proto.Message
	22, // 14: proto.ExecRequest.agent_config:type_name -> google.protobuf.Any
	4,  // 15: proto.ExecResponse.outputs:type_name -> proto.Message
	21, // 16: proto.RegisterAgentRequest.metadata:type_name -> proto.RegisterAgentRequest.MetadataEntry
	11, // 17: proto.RegisterAgentRequest.remote:type_name -> proto.RemoteAgentConfig
	5,  // 18: proto.ListResponse.events:type_name -> proto.ConversationEvent
	25, // 19: proto.GeminiConfig.timeout:type_name -> google.protobuf.Duration
	3,  // 20: proto.AXAgentService.Connect:input_type -> proto.AgentMessage
	7,  // 21: proto.AXAgentService.HealthCheck:input_type -> proto.HealthCheckRequest
	9,  // 22: proto.AXService.Exec:input_type -> proto.ExecRequest
	12, // 23: proto.AXService.RegisterAgent:input_type -> proto.RegisterAgentRequest
	14, // 24: proto.AXEventLogService.List:input_type -> proto.ListRequest
	16, // 25: proto.AXEventLogService.Delete:input_type -> proto.DeleteRequest
	18, // 26: proto.AXEventLogService.Fork:input_type -> proto.ForkRequest
	3,  // 27: proto.AXAgentService.Connect:output_type -> proto.AgentMessage
	8,  // 28: proto.AXAgentService.HealthCheck:output_type -> proto.HealthCheckResponse
	10, // 29: proto.AXService.Exec:output_type -> proto.ExecResponse
	13, // 30: proto.AXService.RegisterAgent:output_type -> proto.RegisterAgentResponse
	15, // 31: proto.AXEventLogService.List:output_type -> proto.ListResponse
	17, // 32: proto.AXEventLogService.Delete:output_type -> proto.DeleteResponse
	19, // 33: proto.AXEventLogService.Fork:output_type -> proto.ForkResponse
	27, // [27:34] is the sub-list for method output_type
	20, // [20:27] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_ax_proto_init() }
func file_proto_ax_proto_init() {
	if File_proto_ax_proto != nil {
		return
	}
	file_proto_content_proto_init()
	file_proto_ax_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_Start)(nil),
		(*AgentMessage_Outputs)(nil),
	}
	file_proto_ax_proto_msgTypes[11].OneofWrappers = []any{
		(*RegisterAgentRequest_Remote)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ax_proto_rawDesc), len(file_proto_ax_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_ax_proto_goTypes,
		DependencyIndexes: file_proto_ax_proto_depIdxs,
		EnumInfos:         file_proto_ax_proto_enumTypes,
		MessageInfos:      file_proto_ax_proto_msgTypes,
	}.Build()
	File_proto_ax_proto = out.File
	file_proto_ax_proto_goTypes = nil
	file_proto_ax_proto_depIdxs = nil
}
