// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: proto/ax.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AXAgentService_Connect_FullMethodName     = "/proto.AXAgentService/Connect"
	AXAgentService_HealthCheck_FullMethodName = "/proto.AXAgentService/HealthCheck"
)

// AXAgentServiceClient is the client API for AXAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AXAgentService defines the gRPC service for agent communication
type AXAgentServiceClient interface {
	// Connect is used by agents to connect to the controller.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, AgentMessage], error)
	// HealthCheck checks if the agent is healthy and responsive
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type aXAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAXAgentServiceClient(cc grpc.ClientConnInterface) AXAgentServiceClient {
	return &aXAgentServiceClient{cc}
}

func (c *aXAgentServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, AgentMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AXAgentService_ServiceDesc.Streams[0], AXAgentService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, AgentMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AXAgentService_ConnectClient = grpc.BidiStreamingClient[AgentMessage, AgentMessage]

func (c *aXAgentServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AXAgentService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AXAgentServiceServer is the server API for AXAgentService service.
// All implementations must embed UnimplementedAXAgentServiceServer
// for forward compatibility.
//
// AXAgentService defines the gRPC service for agent communication
type AXAgentServiceServer interface {
	// Connect is used by agents to connect to the controller.
	Connect(grpc.BidiStreamingServer[AgentMessage, AgentMessage]) error
	// HealthCheck checks if the agent is healthy and responsive
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedAXAgentServiceServer()
}

// UnimplementedAXAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAXAgentServiceServer struct{}

func (UnimplementedAXAgentServiceServer) Connect(grpc.BidiStreamingServer[AgentMessage, AgentMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAXAgentServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAXAgentServiceServer) mustEmbedUnimplementedAXAgentServiceServer() {}
func (UnimplementedAXAgentServiceServer) testEmbeddedByValue()                        {}

// UnsafeAXAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AXAgentServiceServer will
// result in compilation errors.
type UnsafeAXAgentServiceServer interface {
	mustEmbedUnimplementedAXAgentServiceServer()
}

func RegisterAXAgentServiceServer(s grpc.ServiceRegistrar, srv AXAgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAXAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AXAgentService_ServiceDesc, srv)
}

func _AXAgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AXAgentServiceServer).Connect(&grpc.GenericServerStream[AgentMessage, AgentMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AXAgentService_ConnectServer = grpc.BidiStreamingServer[AgentMessage, AgentMessage]

func _AXAgentService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXAgentServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AXAgentService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXAgentServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AXAgentService_ServiceDesc is the grpc.ServiceDesc for AXAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AXAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AXAgentService",
	HandlerType: (*AXAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _AXAgentService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AXAgentService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/ax.proto",
}

const (
	AXService_Exec_FullMethodName          = "/proto.AXService/Exec"
	AXService_RegisterAgent_FullMethodName = "/proto.AXService/RegisterAgent"
)

// AXServiceClient is the client API for AXService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AXService defines the gRPC service for AX operations
type AXServiceClient interface {
	// Exec executes an agentic task or resumes an existing one with streaming responses
	// If the conversation_id already exists, it will be resumed.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecResponse], error)
	// RegisterAgent registers a new agent with the controller
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
}

type aXServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAXServiceClient(cc grpc.ClientConnInterface) AXServiceClient {
	return &aXServiceClient{cc}
}

func (c *aXServiceClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AXService_ServiceDesc.Streams[0], AXService_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AXService_ExecClient = grpc.ServerStreamingClient[ExecResponse]

func (c *aXServiceClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, AXService_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AXServiceServer is the server API for AXService service.
// All implementations must embed UnimplementedAXServiceServer
// for forward compatibility.
//
// AXService defines the gRPC service for AX operations
type AXServiceServer interface {
	// Exec executes an agentic task or resumes an existing one with streaming responses
	// If the conversation_id already exists, it will be resumed.
	Exec(*ExecRequest, grpc.ServerStreamingServer[ExecResponse]) error
	// RegisterAgent registers a new agent with the controller
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	mustEmbedUnimplementedAXServiceServer()
}

// UnimplementedAXServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAXServiceServer struct{}

func (UnimplementedAXServiceServer) Exec(*ExecRequest, grpc.ServerStreamingServer[ExecResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedAXServiceServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedAXServiceServer) mustEmbedUnimplementedAXServiceServer() {}
func (UnimplementedAXServiceServer) testEmbeddedByValue()                   {}

// UnsafeAXServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AXServiceServer will
// result in compilation errors.
type UnsafeAXServiceServer interface {
	mustEmbedUnimplementedAXServiceServer()
}

func RegisterAXServiceServer(s grpc.ServiceRegistrar, srv AXServiceServer) {
	// If the following call pancis, it indicates UnimplementedAXServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AXService_ServiceDesc, srv)
}

func _AXService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AXServiceServer).Exec(m, &grpc.GenericServerStream[ExecRequest, ExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AXService_ExecServer = grpc.ServerStreamingServer[ExecResponse]

func _AXService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AXService_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServiceServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AXService_ServiceDesc is the grpc.ServiceDesc for AXService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AXService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AXService",
	HandlerType: (*AXServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _AXService_RegisterAgent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _AXService_Exec_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/ax.proto",
}

const (
	AXEventLogService_List_FullMethodName   = "/proto.AXEventLogService/List"
	AXEventLogService_Delete_FullMethodName = "/proto.AXEventLogService/Delete"
	AXEventLogService_Fork_FullMethodName   = "/proto.AXEventLogService/Fork"
)

// AXEventLogServiceClient is the client API for AXEventLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AXEventLogServiceClient interface {
	// List conversational events.
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Deletes conversational events and all event log resources
	// for its children executions.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Fork forks an event log from a specific conversation.
	Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*ForkResponse, error)
}

type aXEventLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAXEventLogServiceClient(cc grpc.ClientConnInterface) AXEventLogServiceClient {
	return &aXEventLogServiceClient{cc}
}

func (c *aXEventLogServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, AXEventLogService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXEventLogServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, AXEventLogService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXEventLogServiceClient) Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*ForkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForkResponse)
	err := c.cc.Invoke(ctx, AXEventLogService_Fork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AXEventLogServiceServer is the server API for AXEventLogService service.
// All implementations must embed UnimplementedAXEventLogServiceServer
// for forward compatibility.
type AXEventLogServiceServer interface {
	// List conversational events.
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Deletes conversational events and all event log resources
	// for its children executions.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Fork forks an event log from a specific conversation.
	Fork(context.Context, *ForkRequest) (*ForkResponse, error)
	mustEmbedUnimplementedAXEventLogServiceServer()
}

// UnimplementedAXEventLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAXEventLogServiceServer struct{}

func (UnimplementedAXEventLogServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAXEventLogServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAXEventLogServiceServer) Fork(context.Context, *ForkRequest) (*ForkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fork not implemented")
}
func (UnimplementedAXEventLogServiceServer) mustEmbedUnimplementedAXEventLogServiceServer() {}
func (UnimplementedAXEventLogServiceServer) testEmbeddedByValue()                           {}

// UnsafeAXEventLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AXEventLogServiceServer will
// result in compilation errors.
type UnsafeAXEventLogServiceServer interface {
	mustEmbedUnimplementedAXEventLogServiceServer()
}

func RegisterAXEventLogServiceServer(s grpc.ServiceRegistrar, srv AXEventLogServiceServer) {
	// If the following call pancis, it indicates UnimplementedAXEventLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AXEventLogService_ServiceDesc, srv)
}

func _AXEventLogService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXEventLogServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AXEventLogService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXEventLogServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AXEventLogService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXEventLogServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AXEventLogService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXEventLogServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AXEventLogService_Fork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXEventLogServiceServer).Fork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AXEventLogService_Fork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXEventLogServiceServer).Fork(ctx, req.(*ForkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AXEventLogService_ServiceDesc is the grpc.ServiceDesc for AXEventLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AXEventLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AXEventLogService",
	HandlerType: (*AXEventLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AXEventLogService_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AXEventLogService_Delete_Handler,
		},
		{
			MethodName: "Fork",
			Handler:    _AXEventLogService_Fork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ax.proto",
}
