// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/content.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TextContent represents a text content.
type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_proto_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{0}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ApprovalDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalDecision) Reset() {
	*x = ApprovalDecision{}
	mi := &file_proto_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalDecision) ProtoMessage() {}

func (x *ApprovalDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalDecision.ProtoReflect.Descriptor instead.
func (*ApprovalDecision) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{1}
}

func (x *ApprovalDecision) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type DeclineDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Declined      bool                   `protobuf:"varint,1,opt,name=declined,proto3" json:"declined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineDecision) Reset() {
	*x = DeclineDecision{}
	mi := &file_proto_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineDecision) ProtoMessage() {}

func (x *DeclineDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineDecision.ProtoReflect.Descriptor instead.
func (*DeclineDecision) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{2}
}

func (x *DeclineDecision) GetDeclined() bool {
	if x != nil {
		return x.Declined
	}
	return false
}

type ConfirmationContent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Question string                 `protobuf:"bytes,4,opt,name=question,proto3" json:"question,omitempty"`
	// Types that are valid to be assigned to Decision:
	//
	//	*ConfirmationContent_Approval
	//	*ConfirmationContent_Decline
	Decision      isConfirmationContent_Decision `protobuf_oneof:"decision"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmationContent) Reset() {
	*x = ConfirmationContent{}
	mi := &file_proto_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmationContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmationContent) ProtoMessage() {}

func (x *ConfirmationContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmationContent.ProtoReflect.Descriptor instead.
func (*ConfirmationContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmationContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmationContent) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *ConfirmationContent) GetDecision() isConfirmationContent_Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *ConfirmationContent) GetApproval() *ApprovalDecision {
	if x != nil {
		if x, ok := x.Decision.(*ConfirmationContent_Approval); ok {
			return x.Approval
		}
	}
	return nil
}

func (x *ConfirmationContent) GetDecline() *DeclineDecision {
	if x != nil {
		if x, ok := x.Decision.(*ConfirmationContent_Decline); ok {
			return x.Decline
		}
	}
	return nil
}

type isConfirmationContent_Decision interface {
	isConfirmationContent_Decision()
}

type ConfirmationContent_Approval struct {
	Approval *ApprovalDecision `protobuf:"bytes,5,opt,name=approval,proto3,oneof"`
}

type ConfirmationContent_Decline struct {
	Decline *DeclineDecision `protobuf:"bytes,6,opt,name=decline,proto3,oneof"`
}

func (*ConfirmationContent_Approval) isConfirmationContent_Decision() {}

func (*ConfirmationContent_Decline) isConfirmationContent_Decision() {}

type ToolCallContent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`               // A unique ID for this specific tool call.
	Signature []byte                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"` // A signature hash for backend validation.
	// Types that are valid to be assigned to Type:
	//
	//	*ToolCallContent_FunctionCall
	Type          isToolCallContent_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallContent) Reset() {
	*x = ToolCallContent{}
	mi := &file_proto_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallContent) ProtoMessage() {}

func (x *ToolCallContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallContent.ProtoReflect.Descriptor instead.
func (*ToolCallContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{4}
}

func (x *ToolCallContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCallContent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ToolCallContent) GetType() isToolCallContent_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ToolCallContent) GetFunctionCall() *FunctionCallContent {
	if x != nil {
		if x, ok := x.Type.(*ToolCallContent_FunctionCall); ok {
			return x.FunctionCall
		}
	}
	return nil
}

type isToolCallContent_Type interface {
	isToolCallContent_Type()
}

type ToolCallContent_FunctionCall struct {
	FunctionCall *FunctionCallContent `protobuf:"bytes,2,opt,name=function_call,json=functionCall,proto3,oneof"`
}

func (*ToolCallContent_FunctionCall) isToolCallContent_Type() {}

type ToolResultContent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CallId    string                 `protobuf:"bytes,8,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"` // ID to match the ID from the function call block.
	Signature []byte                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`         // A signature hash for backend validation.
	// Types that are valid to be assigned to Type:
	//
	//	*ToolResultContent_FunctionResult
	Type          isToolResultContent_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultContent) Reset() {
	*x = ToolResultContent{}
	mi := &file_proto_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultContent) ProtoMessage() {}

func (x *ToolResultContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultContent.ProtoReflect.Descriptor instead.
func (*ToolResultContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{5}
}

func (x *ToolResultContent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResultContent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ToolResultContent) GetType() isToolResultContent_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ToolResultContent) GetFunctionResult() *FunctionResultContent {
	if x != nil {
		if x, ok := x.Type.(*ToolResultContent_FunctionResult); ok {
			return x.FunctionResult
		}
	}
	return nil
}

type isToolResultContent_Type interface {
	isToolResultContent_Type()
}

type ToolResultContent_FunctionResult struct {
	FunctionResult *FunctionResultContent `protobuf:"bytes,2,opt,name=function_result,json=functionResult,proto3,oneof"`
}

func (*ToolResultContent_FunctionResult) isToolResultContent_Type() {}

type FunctionCallContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     *structpb.Struct       `protobuf:"bytes,4,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCallContent) Reset() {
	*x = FunctionCallContent{}
	mi := &file_proto_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCallContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCallContent) ProtoMessage() {}

func (x *FunctionCallContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCallContent.ProtoReflect.Descriptor instead.
func (*FunctionCallContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{6}
}

func (x *FunctionCallContent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCallContent) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type FunctionResultContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*FunctionResultContent_Response
	Result        isFunctionResultContent_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionResultContent) Reset() {
	*x = FunctionResultContent{}
	mi := &file_proto_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionResultContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionResultContent) ProtoMessage() {}

func (x *FunctionResultContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionResultContent.ProtoReflect.Descriptor instead.
func (*FunctionResultContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{7}
}

func (x *FunctionResultContent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionResultContent) GetResult() isFunctionResultContent_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FunctionResultContent) GetResponse() *structpb.Struct {
	if x != nil {
		if x, ok := x.Result.(*FunctionResultContent_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isFunctionResultContent_Result interface {
	isFunctionResultContent_Result()
}

type FunctionResultContent_Response struct {
	Response *structpb.Struct `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

func (*FunctionResultContent_Response) isFunctionResultContent_Result() {}

// Content represents a content input or output.
type Content struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Content_Text
	//	*Content_Confirmation
	//	*Content_ToolCall
	//	*Content_ToolResult
	Type          isContent_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_proto_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{8}
}

func (x *Content) GetType() isContent_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Content) GetText() *TextContent {
	if x != nil {
		if x, ok := x.Type.(*Content_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Content) GetConfirmation() *ConfirmationContent {
	if x != nil {
		if x, ok := x.Type.(*Content_Confirmation); ok {
			return x.Confirmation
		}
	}
	return nil
}

func (x *Content) GetToolCall() *ToolCallContent {
	if x != nil {
		if x, ok := x.Type.(*Content_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *Content) GetToolResult() *ToolResultContent {
	if x != nil {
		if x, ok := x.Type.(*Content_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

type isContent_Type interface {
	isContent_Type()
}

type Content_Text struct {
	Text *TextContent `protobuf:"bytes,10,opt,name=text,proto3,oneof"`
}

type Content_Confirmation struct {
	Confirmation *ConfirmationContent `protobuf:"bytes,26,opt,name=confirmation,proto3,oneof"` // TODO(jbd): Remove out of the Content.
}

type Content_ToolCall struct {
	ToolCall *ToolCallContent `protobuf:"bytes,24,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type Content_ToolResult struct {
	ToolResult *ToolResultContent `protobuf:"bytes,25,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

func (*Content_Text) isContent_Type() {}

func (*Content_Confirmation) isContent_Type() {}

func (*Content_ToolCall) isContent_Type() {}

func (*Content_ToolResult) isContent_Type() {}

var File_proto_content_proto protoreflect.FileDescriptor

const file_proto_content_proto_rawDesc = "" +
	"\n" +
	"\x13proto/content.proto\x12\x02ax\x1a\x1cgoogle/protobuf/struct.proto\"3\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04textJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\x04type\".\n" +
	"\x10ApprovalDecision\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\";\n" +
	"\x0fDeclineDecision\x12\x1a\n" +
	"\bdeclined\x18\x01 \x01(\bR\bdeclinedJ\x04\b\x02\x10\x03R\x06reason\"\xc4\x01\n" +
	"\x13ConfirmationContent\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1a\n" +
	"\bquestion\x18\x04 \x01(\tR\bquestion\x122\n" +
	"\bapproval\x18\x05 \x01(\v2\x14.ax.ApprovalDecisionH\x00R\bapproval\x12/\n" +
	"\adecline\x18\x06 \x01(\v2\x13.ax.DeclineDecisionH\x00R\adeclineB\n" +
	"\n" +
	"\bdecisionJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\x04type\"\x87\x01\n" +
	"\x0fToolCallContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tsignature\x18\t \x01(\fR\tsignature\x12>\n" +
	"\rfunction_call\x18\x02 \x01(\v2\x17.ax.FunctionCallContentH\x00R\ffunctionCallB\x06\n" +
	"\x04type\"\x9e\x01\n" +
	"\x11ToolResultContent\x12\x17\n" +
	"\acall_id\x18\b \x01(\tR\x06callId\x12\x1c\n" +
	"\tsignature\x18\t \x01(\fR\tsignature\x12D\n" +
	"\x0ffunction_result\x18\x02 \x01(\v2\x19.ax.FunctionResultContentH\x00R\x0efunctionResultB\x06\n" +
	"\x04typeJ\x04\b\x01\x10\x02\"l\n" +
	"\x13FunctionCallContent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x125\n" +
	"\targuments\x18\x04 \x01(\v2\x17.google.protobuf.StructR\targumentsJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03\"~\n" +
	"\x15FunctionResultContent\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x125\n" +
	"\bresponse\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x00R\bresponseB\b\n" +
	"\x06resultJ\x04\b\x01\x10\x02J\x04\b\x04\x10\x05R\x04type\"\xf7\x01\n" +
	"\aContent\x12%\n" +
	"\x04text\x18\n" +
	" \x01(\v2\x0f.ax.TextContentH\x00R\x04text\x12=\n" +
	"\fconfirmation\x18\x1a \x01(\v2\x17.ax.ConfirmationContentH\x00R\fconfirmation\x122\n" +
	"\ttool_call\x18\x18 \x01(\v2\x13.ax.ToolCallContentH\x00R\btoolCall\x128\n" +
	"\vtool_result\x18\x19 \x01(\v2\x15.ax.ToolResultContentH\x00R\n" +
	"toolResultB\x06\n" +
	"\x04typeJ\x04\b\x01\x10\x05J\x04\b\x06\x10\n" +
	"J\x04\b\v\x10\x18B\x1cZ\x1agithub.com/google/ax/protob\x06proto3"

var (
	file_proto_content_proto_rawDescOnce sync.Once
	file_proto_content_proto_rawDescData []byte
)

func file_proto_content_proto_rawDescGZIP() []byte {
	file_proto_content_proto_rawDescOnce.Do(func() {
		file_proto_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_content_proto_rawDesc), len(file_proto_content_proto_rawDesc)))
	})
	return file_proto_content_proto_rawDescData
}

var file_proto_content_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_content_proto_goTypes = []any{
	(*TextContent)(nil),           // 0: ax.TextContent
	(*ApprovalDecision)(nil),      // 1: ax.ApprovalDecision
	(*DeclineDecision)(nil),       // 2: ax.DeclineDecision
	(*ConfirmationContent)(nil),   // 3: ax.ConfirmationContent
	(*ToolCallContent)(nil),       // 4: ax.ToolCallContent
	(*ToolResultContent)(nil),     // 5: ax.ToolResultContent
	(*FunctionCallContent)(nil),   // 6: ax.FunctionCallContent
	(*FunctionResultContent)(nil), // 7: ax.FunctionResultContent
	(*Content)(nil),               // 8: ax.Content
	(*structpb.Struct)(nil),       // 9: google.protobuf.Struct
}
var file_proto_content_proto_depIdxs = []int32{
	1,  // 0: ax.ConfirmationContent.approval:type_name -> ax.ApprovalDecision
	2,  // 1: ax.ConfirmationContent.decline:type_name -> ax.DeclineDecision
	6,  // 2: ax.ToolCallContent.function_call:type_name -> ax.FunctionCallContent
	7,  // 3: ax.ToolResultContent.function_result:type_name -> ax.FunctionResultContent
	9,  // 4: ax.FunctionCallContent.arguments:type_name -> google.protobuf.Struct
	9,  // 5: ax.FunctionResultContent.response:type_name -> google.protobuf.Struct
	0,  // 6: ax.Content.text:type_name -> ax.TextContent
	3,  // 7: ax.Content.confirmation:type_name -> ax.ConfirmationContent
	4,  // 8: ax.Content.tool_call:type_name -> ax.ToolCallContent
	5,  // 9: ax.Content.tool_result:type_name -> ax.ToolResultContent
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_content_proto_init() }
func file_proto_content_proto_init() {
	if File_proto_content_proto != nil {
		return
	}
	file_proto_content_proto_msgTypes[3].OneofWrappers = []any{
		(*ConfirmationContent_Approval)(nil),
		(*ConfirmationContent_Decline)(nil),
	}
	file_proto_content_proto_msgTypes[4].OneofWrappers = []any{
		(*ToolCallContent_FunctionCall)(nil),
	}
	file_proto_content_proto_msgTypes[5].OneofWrappers = []any{
		(*ToolResultContent_FunctionResult)(nil),
	}
	file_proto_content_proto_msgTypes[7].OneofWrappers = []any{
		(*FunctionResultContent_Response)(nil),
	}
	file_proto_content_proto_msgTypes[8].OneofWrappers = []any{
		(*Content_Text)(nil),
		(*Content_Confirmation)(nil),
		(*Content_ToolCall)(nil),
		(*Content_ToolResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_content_proto_rawDesc), len(file_proto_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_content_proto_goTypes,
		DependencyIndexes: file_proto_content_proto_depIdxs,
		MessageInfos:      file_proto_content_proto_msgTypes,
	}.Build()
	File_proto_content_proto = out.File
	file_proto_content_proto_goTypes = nil
	file_proto_content_proto_depIdxs = nil
}
