// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/content.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TextContent represents a text content.
type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_proto_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{0}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ApprovalDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalDecision) Reset() {
	*x = ApprovalDecision{}
	mi := &file_proto_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalDecision) ProtoMessage() {}

func (x *ApprovalDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalDecision.ProtoReflect.Descriptor instead.
func (*ApprovalDecision) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{1}
}

func (x *ApprovalDecision) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type DeclineDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Declined      bool                   `protobuf:"varint,1,opt,name=declined,proto3" json:"declined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineDecision) Reset() {
	*x = DeclineDecision{}
	mi := &file_proto_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineDecision) ProtoMessage() {}

func (x *DeclineDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineDecision.ProtoReflect.Descriptor instead.
func (*DeclineDecision) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{2}
}

func (x *DeclineDecision) GetDeclined() bool {
	if x != nil {
		return x.Declined
	}
	return false
}

type ConfirmationContent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Question string                 `protobuf:"bytes,4,opt,name=question,proto3" json:"question,omitempty"`
	// Types that are valid to be assigned to Decision:
	//
	//	*ConfirmationContent_Approval
	//	*ConfirmationContent_Decline
	Decision      isConfirmationContent_Decision `protobuf_oneof:"decision"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmationContent) Reset() {
	*x = ConfirmationContent{}
	mi := &file_proto_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmationContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmationContent) ProtoMessage() {}

func (x *ConfirmationContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmationContent.ProtoReflect.Descriptor instead.
func (*ConfirmationContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmationContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmationContent) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *ConfirmationContent) GetDecision() isConfirmationContent_Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *ConfirmationContent) GetApproval() *ApprovalDecision {
	if x != nil {
		if x, ok := x.Decision.(*ConfirmationContent_Approval); ok {
			return x.Approval
		}
	}
	return nil
}

func (x *ConfirmationContent) GetDecline() *DeclineDecision {
	if x != nil {
		if x, ok := x.Decision.(*ConfirmationContent_Decline); ok {
			return x.Decline
		}
	}
	return nil
}

type isConfirmationContent_Decision interface {
	isConfirmationContent_Decision()
}

type ConfirmationContent_Approval struct {
	Approval *ApprovalDecision `protobuf:"bytes,5,opt,name=approval,proto3,oneof"`
}

type ConfirmationContent_Decline struct {
	Decline *DeclineDecision `protobuf:"bytes,6,opt,name=decline,proto3,oneof"`
}

func (*ConfirmationContent_Approval) isConfirmationContent_Decision() {}

func (*ConfirmationContent_Decline) isConfirmationContent_Decision() {}

type FunctionCallContent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args             *structpb.Struct       `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	Id               string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	ThoughtSignature []byte                 `protobuf:"bytes,4,opt,name=thought_signature,json=thoughtSignature,proto3" json:"thought_signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FunctionCallContent) Reset() {
	*x = FunctionCallContent{}
	mi := &file_proto_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCallContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCallContent) ProtoMessage() {}

func (x *FunctionCallContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCallContent.ProtoReflect.Descriptor instead.
func (*FunctionCallContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{4}
}

func (x *FunctionCallContent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCallContent) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *FunctionCallContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FunctionCallContent) GetThoughtSignature() []byte {
	if x != nil {
		return x.ThoughtSignature
	}
	return nil
}

type FunctionResponseContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Response      *structpb.Struct       `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionResponseContent) Reset() {
	*x = FunctionResponseContent{}
	mi := &file_proto_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionResponseContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionResponseContent) ProtoMessage() {}

func (x *FunctionResponseContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionResponseContent.ProtoReflect.Descriptor instead.
func (*FunctionResponseContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{5}
}

func (x *FunctionResponseContent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionResponseContent) GetResponse() *structpb.Struct {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *FunctionResponseContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Content represents a content input or output.
type Content struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*Content_Text
	//	*Content_Confirmation
	//	*Content_FunctionCall
	//	*Content_FunctionResponse
	Content       isContent_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_proto_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{6}
}

func (x *Content) GetContent() isContent_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Content) GetText() *TextContent {
	if x != nil {
		if x, ok := x.Content.(*Content_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Content) GetConfirmation() *ConfirmationContent {
	if x != nil {
		if x, ok := x.Content.(*Content_Confirmation); ok {
			return x.Confirmation
		}
	}
	return nil
}

func (x *Content) GetFunctionCall() *FunctionCallContent {
	if x != nil {
		if x, ok := x.Content.(*Content_FunctionCall); ok {
			return x.FunctionCall
		}
	}
	return nil
}

func (x *Content) GetFunctionResponse() *FunctionResponseContent {
	if x != nil {
		if x, ok := x.Content.(*Content_FunctionResponse); ok {
			return x.FunctionResponse
		}
	}
	return nil
}

type isContent_Content interface {
	isContent_Content()
}

type Content_Text struct {
	Text *TextContent `protobuf:"bytes,10,opt,name=text,proto3,oneof"`
}

type Content_Confirmation struct {
	Confirmation *ConfirmationContent `protobuf:"bytes,26,opt,name=confirmation,proto3,oneof"`
}

type Content_FunctionCall struct {
	FunctionCall *FunctionCallContent `protobuf:"bytes,27,opt,name=function_call,json=functionCall,proto3,oneof"`
}

type Content_FunctionResponse struct {
	FunctionResponse *FunctionResponseContent `protobuf:"bytes,28,opt,name=function_response,json=functionResponse,proto3,oneof"`
}

func (*Content_Text) isContent_Content() {}

func (*Content_Confirmation) isContent_Content() {}

func (*Content_FunctionCall) isContent_Content() {}

func (*Content_FunctionResponse) isContent_Content() {}

var File_proto_content_proto protoreflect.FileDescriptor

const file_proto_content_proto_rawDesc = "" +
	"\n" +
	"\x13proto/content.proto\x12\x05proto\x1a\x1cgoogle/protobuf/struct.proto\"3\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04textJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\x04type\".\n" +
	"\x10ApprovalDecision\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\";\n" +
	"\x0fDeclineDecision\x12\x1a\n" +
	"\bdeclined\x18\x01 \x01(\bR\bdeclinedJ\x04\b\x02\x10\x03R\x06reason\"\xca\x01\n" +
	"\x13ConfirmationContent\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1a\n" +
	"\bquestion\x18\x04 \x01(\tR\bquestion\x125\n" +
	"\bapproval\x18\x05 \x01(\v2\x17.proto.ApprovalDecisionH\x00R\bapproval\x122\n" +
	"\adecline\x18\x06 \x01(\v2\x16.proto.DeclineDecisionH\x00R\adeclineB\n" +
	"\n" +
	"\bdecisionJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\x04type\"\x93\x01\n" +
	"\x13FunctionCallContent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04args\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04args\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12+\n" +
	"\x11thought_signature\x18\x04 \x01(\fR\x10thoughtSignature\"r\n" +
	"\x17FunctionResponseContent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\bresponse\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bresponse\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\xa4\x02\n" +
	"\aContent\x12(\n" +
	"\x04text\x18\n" +
	" \x01(\v2\x12.proto.TextContentH\x00R\x04text\x12@\n" +
	"\fconfirmation\x18\x1a \x01(\v2\x1a.proto.ConfirmationContentH\x00R\fconfirmation\x12A\n" +
	"\rfunction_call\x18\x1b \x01(\v2\x1a.proto.FunctionCallContentH\x00R\ffunctionCall\x12M\n" +
	"\x11function_response\x18\x1c \x01(\v2\x1e.proto.FunctionResponseContentH\x00R\x10functionResponseB\t\n" +
	"\acontentJ\x04\b\x01\x10\x05J\x04\b\x06\x10\n" +
	"J\x04\b\v\x10\x1aB\x1cZ\x1agithub.com/google/ax/protob\x06proto3"

var (
	file_proto_content_proto_rawDescOnce sync.Once
	file_proto_content_proto_rawDescData []byte
)

func file_proto_content_proto_rawDescGZIP() []byte {
	file_proto_content_proto_rawDescOnce.Do(func() {
		file_proto_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_content_proto_rawDesc), len(file_proto_content_proto_rawDesc)))
	})
	return file_proto_content_proto_rawDescData
}

var file_proto_content_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_content_proto_goTypes = []any{
	(*TextContent)(nil),             // 0: proto.TextContent
	(*ApprovalDecision)(nil),        // 1: proto.ApprovalDecision
	(*DeclineDecision)(nil),         // 2: proto.DeclineDecision
	(*ConfirmationContent)(nil),     // 3: proto.ConfirmationContent
	(*FunctionCallContent)(nil),     // 4: proto.FunctionCallContent
	(*FunctionResponseContent)(nil), // 5: proto.FunctionResponseContent
	(*Content)(nil),                 // 6: proto.Content
	(*structpb.Struct)(nil),         // 7: google.protobuf.Struct
}
var file_proto_content_proto_depIdxs = []int32{
	1, // 0: proto.ConfirmationContent.approval:type_name -> proto.ApprovalDecision
	2, // 1: proto.ConfirmationContent.decline:type_name -> proto.DeclineDecision
	7, // 2: proto.FunctionCallContent.args:type_name -> google.protobuf.Struct
	7, // 3: proto.FunctionResponseContent.response:type_name -> google.protobuf.Struct
	0, // 4: proto.Content.text:type_name -> proto.TextContent
	3, // 5: proto.Content.confirmation:type_name -> proto.ConfirmationContent
	4, // 6: proto.Content.function_call:type_name -> proto.FunctionCallContent
	5, // 7: proto.Content.function_response:type_name -> proto.FunctionResponseContent
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_content_proto_init() }
func file_proto_content_proto_init() {
	if File_proto_content_proto != nil {
		return
	}
	file_proto_content_proto_msgTypes[3].OneofWrappers = []any{
		(*ConfirmationContent_Approval)(nil),
		(*ConfirmationContent_Decline)(nil),
	}
	file_proto_content_proto_msgTypes[6].OneofWrappers = []any{
		(*Content_Text)(nil),
		(*Content_Confirmation)(nil),
		(*Content_FunctionCall)(nil),
		(*Content_FunctionResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_content_proto_rawDesc), len(file_proto_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_content_proto_goTypes,
		DependencyIndexes: file_proto_content_proto_depIdxs,
		MessageInfos:      file_proto_content_proto_msgTypes,
	}.Build()
	File_proto_content_proto = out.File
	file_proto_content_proto_goTypes = nil
	file_proto_content_proto_depIdxs = nil
}
