// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: proto/gar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State represents the state of a session
type State int32

const (
	State_STATE_UNSPECIFIED State = 0 // Unspecified state
	State_STATE_RUNNING     State = 1 // Session is currently running
	State_STATE_FAILED      State = 2 // Session failed
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_RUNNING",
		2: "STATE_FAILED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_RUNNING":     1,
		"STATE_FAILED":      2,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gar_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_gar_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{0}
}

// Content represents a message with role, type, mimetype, and data fields
type Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`                                     // The role of the content (e.g., "user", "assistant", "system")
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                     // The type of content (e.g., "text", "image")
	Mimetype      string                 `protobuf:"bytes,3,opt,name=mimetype,proto3" json:"mimetype,omitempty"`                             // MIME type of the data (e.g., "text/plain", "image/png")
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                                     // The actual content data
	CheckpointId  string                 `protobuf:"bytes,5,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"` // Optional: Checkpoint ID for this content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_proto_gar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{0}
}

func (x *Content) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Content) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Content) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *Content) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Content) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

// HealthCheckRequest for agent health checks
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_gar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{1}
}

// HealthCheckResponse contains agent health status
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_gar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TriggerSessionRequest for triggering a new session
type TriggerSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`          // Unique session identifier
	CheckpointId  string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"` // Optional: Resume from specific checkpoint UUID (empty for latest)
	Inputs        []*Content             `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`                                 // Input content to process
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSessionRequest) Reset() {
	*x = TriggerSessionRequest{}
	mi := &file_proto_gar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSessionRequest) ProtoMessage() {}

func (x *TriggerSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSessionRequest.ProtoReflect.Descriptor instead.
func (*TriggerSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TriggerSessionRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *TriggerSessionRequest) GetInputs() []*Content {
	if x != nil {
		return x.Inputs
	}
	return nil
}

// TriggerSessionResponse contains the result of triggering a session
type TriggerSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Session ID (in case it was generated or modified by server)
	State         State                  `protobuf:"varint,2,opt,name=state,proto3,enum=proto.State" json:"state,omitempty"`        // Session state
	Output        *Content               `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`                        // Output content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSessionResponse) Reset() {
	*x = TriggerSessionResponse{}
	mi := &file_proto_gar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSessionResponse) ProtoMessage() {}

func (x *TriggerSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSessionResponse.ProtoReflect.Descriptor instead.
func (*TriggerSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TriggerSessionResponse) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *TriggerSessionResponse) GetOutput() *Content {
	if x != nil {
		return x.Output
	}
	return nil
}

// GetSessionRequest for retrieving session details
type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_proto_gar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// SessionInfo contains session details
type SessionInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	State           State                  `protobuf:"varint,1,opt,name=state,proto3,enum=proto.State" json:"state,omitempty"`
	CurrentStep     int32                  `protobuf:"varint,2,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	ActiveAgents    []string               `protobuf:"bytes,3,rep,name=active_agents,json=activeAgents,proto3" json:"active_agents,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Session creation time
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Last update time
	MessageCount    int32                  `protobuf:"varint,6,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	CheckpointCount int32                  `protobuf:"varint,7,opt,name=checkpoint_count,json=checkpointCount,proto3" json:"checkpoint_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_proto_gar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{6}
}

func (x *SessionInfo) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *SessionInfo) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *SessionInfo) GetActiveAgents() []string {
	if x != nil {
		return x.ActiveAgents
	}
	return nil
}

func (x *SessionInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SessionInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SessionInfo) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SessionInfo) GetCheckpointCount() int32 {
	if x != nil {
		return x.CheckpointCount
	}
	return 0
}

// GetSessionResponse contains session information
type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionInfo           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_proto_gar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{7}
}

func (x *GetSessionResponse) GetSession() *SessionInfo {
	if x != nil {
		return x.Session
	}
	return nil
}

// RegisterAgentRequest for registering an agent
type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // Human-readable name for the agent
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // Description of agent capabilities
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`         // gRPC address for remote agents
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_proto_gar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAgentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterAgentRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterAgentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RegisterAgentResponse contains registration result
type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_proto_gar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{9}
}

// UnregisterAgentRequest for unregistering an agent
type UnregisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentRequest) Reset() {
	*x = UnregisterAgentRequest{}
	mi := &file_proto_gar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentRequest) ProtoMessage() {}

func (x *UnregisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentRequest.ProtoReflect.Descriptor instead.
func (*UnregisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{10}
}

func (x *UnregisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// UnregisterAgentResponse contains unregistration result
type UnregisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentResponse) Reset() {
	*x = UnregisterAgentResponse{}
	mi := &file_proto_gar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentResponse) ProtoMessage() {}

func (x *UnregisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentResponse.ProtoReflect.Descriptor instead.
func (*UnregisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{11}
}

var File_proto_gar_proto protoreflect.FileDescriptor

const file_proto_gar_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/gar.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x01\n" +
	"\aContent\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bmimetype\x18\x03 \x01(\tR\bmimetype\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x12#\n" +
	"\rcheckpoint_id\x18\x05 \x01(\tR\fcheckpointId\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x83\x01\n" +
	"\x15TriggerSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\x12&\n" +
	"\x06inputs\x18\x03 \x03(\v2\x0e.proto.ContentR\x06inputs\"\x83\x01\n" +
	"\x16TriggerSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\"\n" +
	"\x05state\x18\x02 \x01(\x0e2\f.proto.StateR\x05state\x12&\n" +
	"\x06output\x18\x03 \x01(\v2\x0e.proto.ContentR\x06output\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xbf\x02\n" +
	"\vSessionInfo\x12\"\n" +
	"\x05state\x18\x01 \x01(\x0e2\f.proto.StateR\x05state\x12!\n" +
	"\fcurrent_step\x18\x02 \x01(\x05R\vcurrentStep\x12#\n" +
	"\ractive_agents\x18\x03 \x03(\tR\factiveAgents\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12#\n" +
	"\rmessage_count\x18\x06 \x01(\x05R\fmessageCount\x12)\n" +
	"\x10checkpoint_count\x18\a \x01(\x05R\x0fcheckpointCount\"B\n" +
	"\x12GetSessionResponse\x12,\n" +
	"\asession\x18\x01 \x01(\v2\x12.proto.SessionInfoR\asession\"\x85\x02\n" +
	"\x14RegisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12E\n" +
	"\bmetadata\x18\x05 \x03(\v2).proto.RegisterAgentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x17\n" +
	"\x15RegisterAgentResponse\"3\n" +
	"\x16UnregisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x19\n" +
	"\x17UnregisterAgentResponse*C\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x01\x12\x10\n" +
	"\fSTATE_FAILED\x10\x022\x83\x01\n" +
	"\fAgentService\x12-\n" +
	"\aProcess\x12\x0e.proto.Content\x1a\x0e.proto.Content(\x010\x01\x12D\n" +
	"\vHealthCheck\x12\x19.proto.HealthCheckRequest\x1a\x1a.proto.HealthCheckResponse2\xbe\x02\n" +
	"\n" +
	"GARService\x12O\n" +
	"\x0eTriggerSession\x12\x1c.proto.TriggerSessionRequest\x1a\x1d.proto.TriggerSessionResponse0\x01\x12A\n" +
	"\n" +
	"GetSession\x12\x18.proto.GetSessionRequest\x1a\x19.proto.GetSessionResponse\x12J\n" +
	"\rRegisterAgent\x12\x1b.proto.RegisterAgentRequest\x1a\x1c.proto.RegisterAgentResponse\x12P\n" +
	"\x0fUnregisterAgent\x12\x1d.proto.UnregisterAgentRequest\x1a\x1e.proto.UnregisterAgentResponseB\x1dZ\x1bgithub.com/google/gar/protob\x06proto3"

var (
	file_proto_gar_proto_rawDescOnce sync.Once
	file_proto_gar_proto_rawDescData []byte
)

func file_proto_gar_proto_rawDescGZIP() []byte {
	file_proto_gar_proto_rawDescOnce.Do(func() {
		file_proto_gar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gar_proto_rawDesc), len(file_proto_gar_proto_rawDesc)))
	})
	return file_proto_gar_proto_rawDescData
}

var file_proto_gar_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_gar_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_gar_proto_goTypes = []any{
	(State)(0),                      // 0: proto.State
	(*Content)(nil),                 // 1: proto.Content
	(*HealthCheckRequest)(nil),      // 2: proto.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 3: proto.HealthCheckResponse
	(*TriggerSessionRequest)(nil),   // 4: proto.TriggerSessionRequest
	(*TriggerSessionResponse)(nil),  // 5: proto.TriggerSessionResponse
	(*GetSessionRequest)(nil),       // 6: proto.GetSessionRequest
	(*SessionInfo)(nil),             // 7: proto.SessionInfo
	(*GetSessionResponse)(nil),      // 8: proto.GetSessionResponse
	(*RegisterAgentRequest)(nil),    // 9: proto.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),   // 10: proto.RegisterAgentResponse
	(*UnregisterAgentRequest)(nil),  // 11: proto.UnregisterAgentRequest
	(*UnregisterAgentResponse)(nil), // 12: proto.UnregisterAgentResponse
	nil,                             // 13: proto.RegisterAgentRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
}
var file_proto_gar_proto_depIdxs = []int32{
	1,  // 0: proto.TriggerSessionRequest.inputs:type_name -> proto.Content
	0,  // 1: proto.TriggerSessionResponse.state:type_name -> proto.State
	1,  // 2: proto.TriggerSessionResponse.output:type_name -> proto.Content
	0,  // 3: proto.SessionInfo.state:type_name -> proto.State
	14, // 4: proto.SessionInfo.created_at:type_name -> google.protobuf.Timestamp
	14, // 5: proto.SessionInfo.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 6: proto.GetSessionResponse.session:type_name -> proto.SessionInfo
	13, // 7: proto.RegisterAgentRequest.metadata:type_name -> proto.RegisterAgentRequest.MetadataEntry
	1,  // 8: proto.AgentService.Process:input_type -> proto.Content
	2,  // 9: proto.AgentService.HealthCheck:input_type -> proto.HealthCheckRequest
	4,  // 10: proto.GARService.TriggerSession:input_type -> proto.TriggerSessionRequest
	6,  // 11: proto.GARService.GetSession:input_type -> proto.GetSessionRequest
	9,  // 12: proto.GARService.RegisterAgent:input_type -> proto.RegisterAgentRequest
	11, // 13: proto.GARService.UnregisterAgent:input_type -> proto.UnregisterAgentRequest
	1,  // 14: proto.AgentService.Process:output_type -> proto.Content
	3,  // 15: proto.AgentService.HealthCheck:output_type -> proto.HealthCheckResponse
	5,  // 16: proto.GARService.TriggerSession:output_type -> proto.TriggerSessionResponse
	8,  // 17: proto.GARService.GetSession:output_type -> proto.GetSessionResponse
	10, // 18: proto.GARService.RegisterAgent:output_type -> proto.RegisterAgentResponse
	12, // 19: proto.GARService.UnregisterAgent:output_type -> proto.UnregisterAgentResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_gar_proto_init() }
func file_proto_gar_proto_init() {
	if File_proto_gar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gar_proto_rawDesc), len(file_proto_gar_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_gar_proto_goTypes,
		DependencyIndexes: file_proto_gar_proto_depIdxs,
		EnumInfos:         file_proto_gar_proto_enumTypes,
		MessageInfos:      file_proto_gar_proto_msgTypes,
	}.Build()
	File_proto_gar_proto = out.File
	file_proto_gar_proto_goTypes = nil
	file_proto_gar_proto_depIdxs = nil
}
